"""
magic_items.py
Magic items from Magic Item Compendium.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownMagicItemCompendiumMagicItem(StrEnum):
    ARMBANDS_OF_MIGHT = "Armbands of Might"
    CHRONOCHARM_OF_THE_HORIZON_WALKER = "Chronocharm of the Horizon Walker"
    CHRONOCHARM_OF_THE_LAUGHING_ROGUE = "Chronocharm of the Laughing Rogue"
    CRYSTAL_MASK_OF_INSIGHT = "Crystal Mask of Insight"
    CRYSTAL_OF_MIND_CLOAKING_GREATER = "Crystal of Mind Cloaking, Greater"
    DEATHSTRIKE_BRACERS = "Deathstrike Bracers"
    DEMOLITION_CRYSTAL_GREATER = "Demolition Crystal, Greater"
    ETERNAL_WAND_OF_MAGIC_AURA = "Eternal Wand of Magic Aura"
    ETERNAL_WAND_OF_PRESTIDIGITATION = "Eternal Wand of Prestidigitation"
    FIENDSLAYER_CRYSTAL_LEAST = "Fiendslayer Crystal, Least"
    GAUNTLETS_OF_GHOST_FIGHTING = "Gauntlets of Ghost Fighting"
    GITHBORN_TALISMAN = "Githborn Talisman"
    GLOVES_OF_THE_BALANCED_HAND = "Gloves of the Balanced Hand"
    HORN_OF_PLENTY = "Horn of Plenty"
    PHOENIX_CLOAK = "Phoenix Cloak"
    QUICKSILVER_BOOTS = "Quicksilver Boots"
    REVELATION_CRYSTAL_GREATER = "Revelation Crystal, Greater"
    THIRD_EYE_CLARITY = "Third Eye (Clarity)"
    TRUEDEATH_CRYSTAL_GREATER = "Truedeath Crystal, Greater"
    VEST_OF_RESISTANCE_PLUS_1 = "Vest of Resistance +1"
    VEST_OF_RESISTANCE_PLUS_2 = "Vest of Resistance +2"
    VEST_OF_RESISTANCE_PLUS_3 = "Vest of Resistance +3"
    VEST_OF_RESISTANCE_PLUS_4 = "Vest of Resistance +4"
    VEST_OF_RESISTANCE_PLUS_5 = "Vest of Resistance +5"
