"""
magic_items.py
Magic items from Sandstorm.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownSandstormMagicItem(StrEnum):
    SUN_LENSES = "Sun Lenses"
