"""
magic_items/__init__.py
-------------------------
Aggregates per-slot SRD magic-item StrEnums
into a single ``KnownCoreMagicItem``.

AUTO-GENERATED by _gen_magic_item_enums.py.
"""

from heroforge.rules.combine_str_enum import combine
from heroforge.rules.core.magic_items.arms import KnownCoreMagicItemArms
from heroforge.rules.core.magic_items.body import KnownCoreMagicItemBody
from heroforge.rules.core.magic_items.consumable import (
    KnownCoreMagicItemConsumable,
)
from heroforge.rules.core.magic_items.face import KnownCoreMagicItemFace
from heroforge.rules.core.magic_items.feet import KnownCoreMagicItemFeet
from heroforge.rules.core.magic_items.hands import KnownCoreMagicItemHands
from heroforge.rules.core.magic_items.head import KnownCoreMagicItemHead
from heroforge.rules.core.magic_items.ring import KnownCoreMagicItemRing
from heroforge.rules.core.magic_items.shoulders import (
    KnownCoreMagicItemShoulders,
)
from heroforge.rules.core.magic_items.slotless import KnownCoreMagicItemSlotless
from heroforge.rules.core.magic_items.throat import KnownCoreMagicItemThroat
from heroforge.rules.core.magic_items.tool import KnownCoreMagicItemTool
from heroforge.rules.core.magic_items.torso import KnownCoreMagicItemTorso
from heroforge.rules.core.magic_items.waist import KnownCoreMagicItemWaist

KnownCoreMagicItem = combine(
    "KnownCoreMagicItem",
    KnownCoreMagicItemArms,
    KnownCoreMagicItemBody,
    KnownCoreMagicItemConsumable,
    KnownCoreMagicItemFace,
    KnownCoreMagicItemFeet,
    KnownCoreMagicItemHands,
    KnownCoreMagicItemHead,
    KnownCoreMagicItemRing,
    KnownCoreMagicItemShoulders,
    KnownCoreMagicItemSlotless,
    KnownCoreMagicItemThroat,
    KnownCoreMagicItemTool,
    KnownCoreMagicItemTorso,
    KnownCoreMagicItemWaist,
)
