"""
consumable.py
SRD core magic items worn in the consumable slot.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownCoreMagicItemConsumable(StrEnum):
    CANDLE_OF_INVOCATION = "Candle of Invocation"
    CANDLE_OF_TRUTH = "Candle of Truth"
    DUST_OF_APPEARANCE = "Dust of Appearance"
    DUST_OF_DISAPPEARANCE = "Dust of Disappearance"
    DUST_OF_DRYNESS = "Dust of Dryness"
    DUST_OF_ILLUSION = "Dust of Illusion"
    DUST_OF_TRACELESSNESS = "Dust of Tracelessness"
    ELIXIR_OF_FIRE_BREATH = "Elixir of Fire Breath"
    ELIXIR_OF_HIDING = "Elixir of Hiding"
    ELIXIR_OF_LOVE = "Elixir of Love"
    ELIXIR_OF_SNEAKING = "Elixir of Sneaking"
    ELIXIR_OF_SWIMMING = "Elixir of Swimming"
    ELIXIR_OF_TRUTH = "Elixir of Truth"
    ELIXIR_OF_VISION = "Elixir of Vision"
    MANUAL_OF_BODILY_HEALTH_PLUS_1 = "Manual of Bodily Health +1"
    MANUAL_OF_BODILY_HEALTH_PLUS_2 = "Manual of Bodily Health +2"
    MANUAL_OF_BODILY_HEALTH_PLUS_3 = "Manual of Bodily Health +3"
    MANUAL_OF_BODILY_HEALTH_PLUS_4 = "Manual of Bodily Health +4"
    MANUAL_OF_BODILY_HEALTH_PLUS_5 = "Manual of Bodily Health +5"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_1 = "Manual of Gainful Exercise +1"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_2 = "Manual of Gainful Exercise +2"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_3 = "Manual of Gainful Exercise +3"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_4 = "Manual of Gainful Exercise +4"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_5 = "Manual of Gainful Exercise +5"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_1 = "Manual of Quickness of Action +1"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_2 = "Manual of Quickness of Action +2"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_3 = "Manual of Quickness of Action +3"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_4 = "Manual of Quickness of Action +4"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_5 = "Manual of Quickness of Action +5"
    QUAALS_FEATHER_TOKEN_ANCHOR = "Quaal's Feather Token (Anchor)"
    QUAALS_FEATHER_TOKEN_BIRD = "Quaal's Feather Token (Bird)"
    QUAALS_FEATHER_TOKEN_FAN = "Quaal's Feather Token (Fan)"
    QUAALS_FEATHER_TOKEN_SWAN_BOAT = "Quaal's Feather Token (Swan Boat)"
    QUAALS_FEATHER_TOKEN_TREE = "Quaal's Feather Token (Tree)"
    QUAALS_FEATHER_TOKEN_WHIP = "Quaal's Feather Token (Whip)"
    RESTORATIVE_OINTMENT = "Restorative Ointment"
    SALVE_OF_SLIPPERINESS = "Salve of Slipperiness"
    SILVERSHEEN = "Silversheen"
    SOVEREIGN_GLUE = "Sovereign Glue"
    STONE_SALVE = "Stone Salve"
    TOME_OF_CLEAR_THOUGHT_PLUS_1 = "Tome of Clear Thought +1"
    TOME_OF_CLEAR_THOUGHT_PLUS_2 = "Tome of Clear Thought +2"
    TOME_OF_CLEAR_THOUGHT_PLUS_3 = "Tome of Clear Thought +3"
    TOME_OF_CLEAR_THOUGHT_PLUS_4 = "Tome of Clear Thought +4"
    TOME_OF_CLEAR_THOUGHT_PLUS_5 = "Tome of Clear Thought +5"
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_1 = (
        "Tome of Leadership and Influence +1"
    )
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_2 = (
        "Tome of Leadership and Influence +2"
    )
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_3 = (
        "Tome of Leadership and Influence +3"
    )
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_4 = (
        "Tome of Leadership and Influence +4"
    )
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_5 = (
        "Tome of Leadership and Influence +5"
    )
    TOME_OF_UNDERSTANDING_PLUS_1 = "Tome of Understanding +1"
    TOME_OF_UNDERSTANDING_PLUS_2 = "Tome of Understanding +2"
    TOME_OF_UNDERSTANDING_PLUS_3 = "Tome of Understanding +3"
    TOME_OF_UNDERSTANDING_PLUS_4 = "Tome of Understanding +4"
    TOME_OF_UNDERSTANDING_PLUS_5 = "Tome of Understanding +5"
    UNGUENT_OF_TIMELESSNESS = "Unguent of Timelessness"
    UNIVERSAL_SOLVENT = "Universal Solvent"
