"""
torso.py
SRD core magic items worn in the torso slot.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownCoreMagicItemTorso(StrEnum):
    DRUIDS_VESTMENT = "Druid's Vestment"
    VEST_OF_ESCAPE = "Vest of Escape"
