"""
waist.py
SRD core magic items worn in the waist slot.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownCoreMagicItemWaist(StrEnum):
    BELT_OF_DWARVENKIND = "Belt of Dwarvenkind"
    BELT_OF_GIANT_STRENGTH_PLUS_2 = "Belt of Giant Strength +2"
    BELT_OF_GIANT_STRENGTH_PLUS_4 = "Belt of Giant Strength +4"
    BELT_OF_GIANT_STRENGTH_PLUS_6 = "Belt of Giant Strength +6"
    MONKS_BELT = "Monk's Belt"
