"""
magic_items.py
Custom magic items.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownCustomMagicItem(StrEnum):
    RING_OF_THARIZDUN = "Ring of Tharizdun"
    SZIRBS_SHINING_HELM = "Szirb's Shining Helm"
    THIEVES_TOOLS_MASTERWORK = "Thieves' Tools, Masterwork"
    XAN_IBNDUMAN = "Xan ibn'Duman"
