"""
magic_items.py
Custom magic items.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit custom/magic_items.yaml and rerun
``uv run check-magic-items --fix``.
"""

from __future__ import annotations

from enum import StrEnum


class KnownCustomMagicItem(StrEnum):
    ARMBANDS_OF_MIGHT = "Armbands of Might"
    BELT_OF_MAGNIFICENCE_PLUS_2 = "Belt of Magnificence +2"
    BELT_OF_MAGNIFICENCE_PLUS_4 = "Belt of Magnificence +4"
    BELT_OF_MAGNIFICENCE_PLUS_6 = "Belt of Magnificence +6"
    CHRONOCHARM_OF_THE_HORIZON_WALKER = "Chronocharm of the Horizon Walker"
    CHRONOCHARM_OF_THE_LAUGHING_ROGUE = "Chronocharm of the Laughing Rogue"
    CLOAK_OF_COMFORT_PLUS_1 = "Cloak of Comfort +1"
    CLOAK_OF_COMFORT_PLUS_2 = "Cloak of Comfort +2"
    CLOAK_OF_COMFORT_PLUS_3 = "Cloak of Comfort +3"
    CLOAK_OF_COMFORT_PLUS_4 = "Cloak of Comfort +4"
    CLOAK_OF_COMFORT_PLUS_5 = "Cloak of Comfort +5"
    CRYSTAL_MASK_OF_INSIGHT = "Crystal Mask of Insight"
    CRYSTAL_OF_MIND_CLOAKING_GREATER = "Crystal of Mind Cloaking, Greater"
    DEATHSTRIKE_BRACERS = "Deathstrike Bracers"
    DEMOLITION_CRYSTAL_GREATER = "Demolition Crystal, Greater"
    EARTHSILK_ROPE = "Earthsilk Rope"
    ETERNAL_WAND_OF_MAGIC_AURA = "Eternal Wand of Magic Aura"
    ETERNAL_WAND_OF_PRESTIDIGITATION = "Eternal Wand of Prestidigitation"
    FIENDSLAYER_CRYSTAL_LEAST = "Fiendslayer Crystal, Least"
    GAUNTLETS_OF_GHOST_FIGHTING = "Gauntlets of Ghost Fighting"
    GEMSTONE_OF_HEAVY_FORTIFICATION = "Gemstone of Heavy Fortification"
    GITHBORN_TALISMAN = "Githborn Talisman"
    GLOVES_OF_THE_BALANCED_HAND = "Gloves of the Balanced Hand"
    HEARTSTONE = "Heartstone"
    HERALDIC_CREST_OF_COURAGE = "Heraldic Crest of Courage"
    HEWARDS_FORTIFYING_BEDROLL = "Heward's Fortifying Bedroll"
    HORN_OF_PLENTY = "Horn of Plenty"
    PHOENIX_CLOAK = "Phoenix Cloak"
    QUICKSILVER_BOOTS = "Quicksilver Boots"
    REVELATION_CRYSTAL_GREATER = "Revelation Crystal, Greater"
    RING_OF_THARIZDUN = "Ring of Tharizdun"
    ROD_OF_EXTEND_LESSER = "Rod of Extend, Lesser"
    SUN_LENSES = "Sun Lenses"
    SZIRBS_SHINING_HELM = "Szirb's Shining Helm"
    THIEVES_TOOLS_MASTERWORK = "Thieves' Tools, Masterwork"
    THIRD_EYE_CLARITY = "Third Eye (Clarity)"
    TRUEDEATH_CRYSTAL_GREATER = "Truedeath Crystal, Greater"
    VEST_OF_RESISTANCE_PLUS_1 = "Vest of Resistance +1"
    VEST_OF_RESISTANCE_PLUS_2 = "Vest of Resistance +2"
    VEST_OF_RESISTANCE_PLUS_3 = "Vest of Resistance +3"
    VEST_OF_RESISTANCE_PLUS_4 = "Vest of Resistance +4"
    VEST_OF_RESISTANCE_PLUS_5 = "Vest of Resistance +5"
    XAN_IBNDUMAN = "Xan ibn'Duman"
