"""
magic_items.py
Magic items from Draconomicon.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownDraconomiconMagicItem(StrEnum):
    GEMSTONE_OF_HEAVY_FORTIFICATION = "Gemstone of Heavy Fortification"
