"""
magic_items.py
Magic items from Complete Mage.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownCompleteMageMagicItem(StrEnum):
    CLOAK_OF_COMFORT_PLUS_1 = "Cloak of Comfort +1"
    CLOAK_OF_COMFORT_PLUS_2 = "Cloak of Comfort +2"
    CLOAK_OF_COMFORT_PLUS_3 = "Cloak of Comfort +3"
    CLOAK_OF_COMFORT_PLUS_4 = "Cloak of Comfort +4"
    CLOAK_OF_COMFORT_PLUS_5 = "Cloak of Comfort +5"
    HEWARDS_FORTIFYING_BEDROLL = "Heward's Fortifying Bedroll"
