"""
magic_items.py
Magic items from Heroes Of Battle.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownHeroesOfBattleMagicItem(StrEnum):
    HERALDIC_CREST_OF_COURAGE = "Heraldic Crest of Courage"
