"""
buffs.py
SRD core buffs (spells, items, feats, etc).
"""

from __future__ import annotations

from enum import StrEnum


class KnownCoreBuff(StrEnum):
    AID = "Aid"
    AMULET_OF_HEALTH_PLUS_2 = "Amulet of Health +2"
    AMULET_OF_HEALTH_PLUS_4 = "Amulet of Health +4"
    AMULET_OF_HEALTH_PLUS_6 = "Amulet of Health +6"
    AMULET_OF_MIGHTY_FISTS_PLUS_1 = "Amulet of Mighty Fists +1"
    AMULET_OF_MIGHTY_FISTS_PLUS_2 = "Amulet of Mighty Fists +2"
    AMULET_OF_MIGHTY_FISTS_PLUS_3 = "Amulet of Mighty Fists +3"
    AMULET_OF_MIGHTY_FISTS_PLUS_4 = "Amulet of Mighty Fists +4"
    AMULET_OF_MIGHTY_FISTS_PLUS_5 = "Amulet of Mighty Fists +5"
    AMULET_OF_NATURAL_ARMOR_PLUS_1 = "Amulet of Natural Armor +1"
    AMULET_OF_NATURAL_ARMOR_PLUS_2 = "Amulet of Natural Armor +2"
    AMULET_OF_NATURAL_ARMOR_PLUS_3 = "Amulet of Natural Armor +3"
    AMULET_OF_NATURAL_ARMOR_PLUS_4 = "Amulet of Natural Armor +4"
    AMULET_OF_NATURAL_ARMOR_PLUS_5 = "Amulet of Natural Armor +5"
    AMULET_OF_PROOF_AGAINST_DETECTION_AND_LOCATION = (
        "Amulet of Proof against Detection and Location"
    )
    AMULET_OF_THE_PLANES = "Amulet of the Planes"
    APPARATUS_OF_THE_CRAB = "Apparatus of the Crab"
    BAG_OF_HOLDING_TYPE_I = "Bag of Holding (Type I)"
    BAG_OF_HOLDING_TYPE_II = "Bag of Holding (Type II)"
    BAG_OF_HOLDING_TYPE_III = "Bag of Holding (Type III)"
    BAG_OF_HOLDING_TYPE_IV = "Bag of Holding (Type IV)"
    BAG_OF_TRICKS_GRAY = "Bag of Tricks (Gray)"
    BAG_OF_TRICKS_RUST = "Bag of Tricks (Rust)"
    BAG_OF_TRICKS_TAN = "Bag of Tricks (Tan)"
    BARBARIAN_FAST_MOVEMENT = "Barbarian fast_movement"
    BARBARIAN_RAGE = "Barbarian Rage"
    BARKSKIN = "Barkskin"
    BEAD_OF_FORCE = "Bead of Force"
    BEARS_ENDURANCE = "Bear's Endurance"
    BELT_OF_DWARVENKIND = "Belt of Dwarvenkind"
    BELT_OF_GIANT_STRENGTH_PLUS_2 = "Belt of Giant Strength +2"
    BELT_OF_GIANT_STRENGTH_PLUS_4 = "Belt of Giant Strength +4"
    BELT_OF_GIANT_STRENGTH_PLUS_6 = "Belt of Giant Strength +6"
    BLACKGUARD_DARK_BLESSING = "Blackguard dark_blessing"
    BLESS = "Bless"
    BLESS_WEAPON = "Bless Weapon"
    BLESSED_BOOK = "Blessed Book"
    BOOTS_OF_ELVENKIND = "Boots of Elvenkind"
    BOOTS_OF_LEVITATION = "Boots of Levitation"
    BOOTS_OF_SPEED = "Boots of Speed"
    BOOTS_OF_STRIDING_AND_SPRINGING = "Boots of Striding and Springing"
    BOOTS_OF_TELEPORTATION = "Boots of Teleportation"
    BOOTS_OF_THE_WINTERLANDS = "Boots of the Winterlands"
    BOTTLE_OF_AIR = "Bottle of Air"
    BOWL_OF_COMMANDING_WATER_ELEMENTALS = "Bowl of Commanding Water Elementals"
    BRACELET_OF_FRIENDS = "Bracelet of Friends"
    BRACERS_OF_ARCHERY_GREATER = "Bracers of Archery (Greater)"
    BRACERS_OF_ARCHERY_LESSER = "Bracers of Archery (Lesser)"
    BRACERS_OF_ARMOR_PLUS_1 = "Bracers of Armor +1"
    BRACERS_OF_ARMOR_PLUS_2 = "Bracers of Armor +2"
    BRACERS_OF_ARMOR_PLUS_3 = "Bracers of Armor +3"
    BRACERS_OF_ARMOR_PLUS_4 = "Bracers of Armor +4"
    BRACERS_OF_ARMOR_PLUS_5 = "Bracers of Armor +5"
    BRACERS_OF_ARMOR_PLUS_6 = "Bracers of Armor +6"
    BRACERS_OF_ARMOR_PLUS_7 = "Bracers of Armor +7"
    BRACERS_OF_ARMOR_PLUS_8 = "Bracers of Armor +8"
    BRAZIER_OF_COMMANDING_FIRE_ELEMENTALS = (
        "Brazier of Commanding Fire Elementals"
    )
    BROOCH_OF_SHIELDING = "Brooch of Shielding"
    BROOM_OF_FLYING = "Broom of Flying"
    BULLS_STRENGTH = "Bull's Strength"
    CANDLE_OF_INVOCATION = "Candle of Invocation"
    CANDLE_OF_TRUTH = "Candle of Truth"
    CAPE_OF_THE_MOUNTEBANK = "Cape of the Mountebank"
    CARPET_OF_FLYING_10X10 = "Carpet of Flying (10x10)"
    CARPET_OF_FLYING_5X10 = "Carpet of Flying (5x10)"
    CARPET_OF_FLYING_5X5 = "Carpet of Flying (5x5)"
    CARPET_OF_FLYING_6X9 = "Carpet of Flying (6x9)"
    CATS_GRACE = "Cat's Grace"
    CENSER_OF_CONTROLLING_AIR_ELEMENTALS = (
        "Censer of Controlling Air Elementals"
    )
    CHAOS_DIAMOND = "Chaos Diamond"
    CHIME_OF_INTERRUPTION = "Chime of Interruption"
    CHIME_OF_OPENING = "Chime of Opening"
    CIRCLET_OF_BLASTING_MAJOR = "Circlet of Blasting (Major)"
    CIRCLET_OF_BLASTING_MINOR = "Circlet of Blasting (Minor)"
    CIRCLET_OF_PERSUASION = "Circlet of Persuasion"
    CLOAK_OF_ARACHNIDA = "Cloak of Arachnida"
    CLOAK_OF_CHAOS = "Cloak of Chaos"
    CLOAK_OF_CHARISMA_PLUS_2 = "Cloak of Charisma +2"
    CLOAK_OF_CHARISMA_PLUS_4 = "Cloak of Charisma +4"
    CLOAK_OF_CHARISMA_PLUS_6 = "Cloak of Charisma +6"
    CLOAK_OF_DISPLACEMENT_MAJOR = "Cloak of Displacement (Major)"
    CLOAK_OF_DISPLACEMENT_MINOR = "Cloak of Displacement (Minor)"
    CLOAK_OF_ELVENKIND = "Cloak of Elvenkind"
    CLOAK_OF_ETHEREALNESS = "Cloak of Etherealness"
    CLOAK_OF_RESISTANCE_PLUS_1 = "Cloak of Resistance +1"
    CLOAK_OF_RESISTANCE_PLUS_2 = "Cloak of Resistance +2"
    CLOAK_OF_RESISTANCE_PLUS_3 = "Cloak of Resistance +3"
    CLOAK_OF_RESISTANCE_PLUS_4 = "Cloak of Resistance +4"
    CLOAK_OF_RESISTANCE_PLUS_5 = "Cloak of Resistance +5"
    CLOAK_OF_THE_BAT = "Cloak of the Bat"
    CLOAK_OF_THE_MANTA_RAY = "Cloak of the Manta Ray"
    CONFUSED = "Confused"
    COWERING = "Cowering"
    CRYSTAL_BALL = "Crystal Ball"
    CRYSTAL_BALL_DETECT_THOUGHTS = "Crystal Ball (Detect Thoughts)"
    CRYSTAL_BALL_SEE_INVISIBILITY = "Crystal Ball (See Invisibility)"
    CRYSTAL_BALL_TELEPATHY = "Crystal Ball (Telepathy)"
    CRYSTAL_BALL_TRUE_SEEING = "Crystal Ball (True Seeing)"
    CUBE_OF_FORCE = "Cube of Force"
    CUBE_OF_FROST_RESISTANCE = "Cube of Frost Resistance"
    CUBIC_GATE = "Cubic Gate"
    DARKSKULL = "Darkskull"
    DAZED = "Dazed"
    DEAFENED = "Deafened"
    DECANTER_OF_ENDLESS_WATER = "Decanter of Endless Water"
    DECK_OF_ILLUSIONS = "Deck of Illusions"
    DEFENSIVE_STANCE = "Defensive Stance"
    DIMENSIONAL_SHACKLES = "Dimensional Shackles"
    DISABLED = "Disabled"
    DIVINE_FAVOR = "Divine Favor"
    DIVINE_POWER = "Divine Power"
    DODGE = "Dodge"
    DOOM = "Doom"
    DRAGON_DISCIPLE_NATURAL_ARMOR_1 = "Dragon Disciple natural_armor_1"
    DRAGON_DISCIPLE_NATURAL_ARMOR_4 = "Dragon Disciple natural_armor_4"
    DRAGON_DISCIPLE_NATURAL_ARMOR_7 = "Dragon Disciple natural_armor_7"
    DRAGON_DISCIPLE_STR_INCREASE_2 = "Dragon Disciple str_increase_2"
    DRAGON_DISCIPLE_STR_INCREASE_4 = "Dragon Disciple str_increase_4"
    DRUIDS_VESTMENT = "Druid's Vestment"
    DRUMS_OF_PANIC = "Drums of Panic"
    DUELIST_CANNY_DEFENSE = "Duelist canny_defense"
    DUELIST_GRACE = "Duelist grace"
    DUELIST_IMPROVED_REACTION = "Duelist improved_reaction"
    DUST_OF_APPEARANCE = "Dust of Appearance"
    DUST_OF_DISAPPEARANCE = "Dust of Disappearance"
    DUST_OF_DRYNESS = "Dust of Dryness"
    DUST_OF_ILLUSION = "Dust of Illusion"
    DUST_OF_TRACELESSNESS = "Dust of Tracelessness"
    DYING = "Dying"
    EAGLES_SPLENDOR = "Eagle's Splendor"
    EFFICIENT_QUIVER = "Efficient Quiver"
    EFREETI_BOTTLE = "Efreeti Bottle"
    ELEMENTAL_GEM = "Elemental Gem"
    ELIXIR_OF_FIRE_BREATH = "Elixir of Fire Breath"
    ELIXIR_OF_HIDING = "Elixir of Hiding"
    ELIXIR_OF_LOVE = "Elixir of Love"
    ELIXIR_OF_SNEAKING = "Elixir of Sneaking"
    ELIXIR_OF_SWIMMING = "Elixir of Swimming"
    ELIXIR_OF_TRUTH = "Elixir of Truth"
    ELIXIR_OF_VISION = "Elixir of Vision"
    ENERGY_DRAINED = "Energy Drained"
    ENLARGE_PERSON = "Enlarge Person"
    EVERSMOKING_BOTTLE = "Eversmoking Bottle"
    EXPEDITIOUS_RETREAT = "Expeditious Retreat"
    EYES_OF_CHARMING = "Eyes of Charming"
    EYES_OF_DOOM = "Eyes of Doom"
    EYES_OF_PETRIFICATION = "Eyes of Petrification"
    EYES_OF_THE_EAGLE = "Eyes of the Eagle"
    FALSE_LIFE = "False Life"
    FASCINATED = "Fascinated"
    FAVORED_ENEMY_PLUS_2 = "Favored Enemy +2"
    FAVORED_ENEMY_PLUS_4 = "Favored Enemy +4"
    FAVORED_ENEMY_PLUS_6 = "Favored Enemy +6"
    FEATHER_TOKEN_ANCHOR = "Feather Token (Anchor)"
    FEATHER_TOKEN_BIRD = "Feather Token (Bird)"
    FEATHER_TOKEN_FAN = "Feather Token (Fan)"
    FEATHER_TOKEN_SWAN_BOAT = "Feather Token (Swan Boat)"
    FEATHER_TOKEN_TREE = "Feather Token (Tree)"
    FEATHER_TOKEN_WHIP = "Feather Token (Whip)"
    FIGURINE_OF_WONDROUS_POWER_BRONZE_GRIFFON = (
        "Figurine of Wondrous Power (Bronze Griffon)"
    )
    FIGURINE_OF_WONDROUS_POWER_EBONY_FLY = (
        "Figurine of Wondrous Power (Ebony Fly)"
    )
    FIGURINE_OF_WONDROUS_POWER_GOLDEN_LIONS = (
        "Figurine of Wondrous Power (Golden Lions)"
    )
    FIGURINE_OF_WONDROUS_POWER_IVORY_GOATS = (
        "Figurine of Wondrous Power (Ivory Goats)"
    )
    FIGURINE_OF_WONDROUS_POWER_MARBLE_ELEPHANT = (
        "Figurine of Wondrous Power (Marble Elephant)"
    )
    FIGURINE_OF_WONDROUS_POWER_OBSIDIAN_STEED = (
        "Figurine of Wondrous Power (Obsidian Steed)"
    )
    FIGURINE_OF_WONDROUS_POWER_ONYX_DOG = (
        "Figurine of Wondrous Power (Onyx Dog)"
    )
    FIGURINE_OF_WONDROUS_POWER_SERPENTINE_OWL = (
        "Figurine of Wondrous Power (Serpentine Owl)"
    )
    FIGURINE_OF_WONDROUS_POWER_SILVER_RAVEN = (
        "Figurine of Wondrous Power (Silver Raven)"
    )
    FLAT_FOOTED = "Flat-Footed"
    FLURRY_OF_BLOWS = "Flurry of Blows"
    FOLDING_BOAT = "Folding Boat"
    FORESIGHT = "Foresight"
    FOXS_CUNNING = "Fox's Cunning"
    GAUNTLET_OF_RUST = "Gauntlet of Rust"
    GAUNTLETS_OF_OGRE_POWER = "Gauntlets of Ogre Power"
    GEM_OF_BRIGHTNESS = "Gem of Brightness"
    GEM_OF_SEEING = "Gem of Seeing"
    GLOVE_OF_STORING = "Glove of Storing"
    GLOVES_OF_ARROW_SNARING = "Gloves of Arrow Snaring"
    GLOVES_OF_DEXTERITY_PLUS_2 = "Gloves of Dexterity +2"
    GLOVES_OF_DEXTERITY_PLUS_4 = "Gloves of Dexterity +4"
    GLOVES_OF_DEXTERITY_PLUS_6 = "Gloves of Dexterity +6"
    GLOVES_OF_SWIMMING_AND_CLIMBING = "Gloves of Swimming and Climbing"
    GOGGLES_OF_MINUTE_SEEING = "Goggles of Minute Seeing"
    GOGGLES_OF_NIGHT = "Goggles of Night"
    GOLEM_MANUAL_CLAY = "Golem Manual (Clay)"
    GOLEM_MANUAL_FLESH = "Golem Manual (Flesh)"
    GOLEM_MANUAL_GREATER_STONE = "Golem Manual (Greater Stone)"
    GOLEM_MANUAL_IRON = "Golem Manual (Iron)"
    GOLEM_MANUAL_STONE = "Golem Manual (Stone)"
    GOLEMBANE_SCARAB = "Golembane Scarab"
    GOOD_HOPE = "Good Hope"
    GRAPPLING = "Grappling"
    GREATER_RAGE = "Greater Rage"
    GUIDANCE = "Guidance"
    HAND_OF_GLORY = "Hand of Glory"
    HAND_OF_THE_MAGE = "Hand of the Mage"
    HANDY_HAVERSACK = "Handy Haversack"
    HARP_OF_CHARMING = "Harp of Charming"
    HASTE = "Haste"
    HAT_OF_DISGUISE = "Hat of Disguise"
    HEADBAND_OF_INTELLECT_PLUS_2 = "Headband of Intellect +2"
    HEADBAND_OF_INTELLECT_PLUS_4 = "Headband of Intellect +4"
    HEADBAND_OF_INTELLECT_PLUS_6 = "Headband of Intellect +6"
    HELM_OF_BRILLIANCE = "Helm of Brilliance"
    HELM_OF_COMPREHEND_LANGUAGES_AND_READ_MAGIC = (
        "Helm of Comprehend Languages and Read Magic"
    )
    HELM_OF_TELEPATHY = "Helm of Telepathy"
    HELM_OF_TELEPORTATION = "Helm of Teleportation"
    HELM_OF_UNDERWATER_ACTION = "Helm of Underwater Action"
    HELPLESS = "Helpless"
    HEROISM = "Heroism"
    HEROISM_GREATER = "Heroism (Greater)"
    HOLY_AURA = "Holy Aura"
    HORN_OF_BLASTING = "Horn of Blasting"
    HORN_OF_BLASTING_GREATER = "Horn of Blasting (Greater)"
    HORN_OF_FOG = "Horn of Fog"
    HORN_OF_GOODNESS_EVIL = "Horn of Goodness/Evil"
    HORN_OF_THE_TRITONS = "Horn of the Tritons"
    HORN_OF_VALHALLA = "Horn of Valhalla"
    HORSESHOES_OF_A_ZEPHYR = "Horseshoes of a Zephyr"
    HORSESHOES_OF_SPEED = "Horseshoes of Speed"
    INCENSE_OF_MEDITATION = "Incense of Meditation"
    INSPIRE_COURAGE_PLUS_1 = "Inspire Courage +1"
    INSPIRE_COURAGE_PLUS_2 = "Inspire Courage +2"
    INSPIRE_COURAGE_PLUS_3 = "Inspire Courage +3"
    INSPIRE_COURAGE_PLUS_4 = "Inspire Courage +4"
    INSPIRE_GREATNESS = "Inspire Greatness"
    INSTANT_FORTRESS = "Instant Fortress"
    INVISIBILITY = "Invisibility"
    INVISIBLE = "Invisible"
    IOUN_STONE_CLEAR_SPINDLE = "Ioun Stone (Clear Spindle)"
    IOUN_STONE_DARK_BLUE_RHOMBOID = "Ioun Stone (Dark Blue Rhomboid)"
    IOUN_STONE_DEEP_RED_SPHERE = "Ioun Stone (Deep Red Sphere)"
    IOUN_STONE_DUSTY_ROSE_PRISM = "Ioun Stone (Dusty Rose Prism)"
    IOUN_STONE_INCANDESCENT_BLUE_SPHERE = (
        "Ioun Stone (Incandescent Blue Sphere)"
    )
    IOUN_STONE_IRIDESCENT_SPINDLE = "Ioun Stone (Iridescent Spindle)"
    IOUN_STONE_LAVENDER_AND_GREEN_ELLIPSOID = (
        "Ioun Stone (Lavender and Green Ellipsoid)"
    )
    IOUN_STONE_ORANGE = "Ioun Stone (Orange)"
    IOUN_STONE_PALE_BLUE_RHOMBOID = "Ioun Stone (Pale Blue Rhomboid)"
    IOUN_STONE_PALE_GREEN_PRISM = "Ioun Stone (Pale Green Prism)"
    IOUN_STONE_PALE_LAVENDER_ELLIPSOID = "Ioun Stone (Pale Lavender Ellipsoid)"
    IOUN_STONE_PEARLY_WHITE_SPINDLE = "Ioun Stone (Pearly White Spindle)"
    IOUN_STONE_PINK_AND_GREEN_SPHERE = "Ioun Stone (Pink and Green Sphere)"
    IOUN_STONE_PINK_RHOMBOID = "Ioun Stone (Pink Rhomboid)"
    IOUN_STONE_SCARLET_AND_BLUE_SPHERE = "Ioun Stone (Scarlet and Blue Sphere)"
    IOUN_STONE_VIBRANT_PURPLE_PRISM = "Ioun Stone (Vibrant Purple Prism)"
    IRON_BANDS_OF_BINDING = "Iron Bands of Binding"
    IRON_BODY = "Iron Body"
    IRON_FLASK = "Iron Flask"
    JUMP = "Jump"
    LANTERN_OF_REVEALING = "Lantern of Revealing"
    LENS_OF_DETECTION = "Lens of Detection"
    LONGSTRIDER = "Longstrider"
    LYRE_OF_BUILDING = "Lyre of Building"
    MAGE_ARMOR = "Mage Armor"
    MAGIC_CIRCLE_AGAINST_CHAOS = "Magic Circle against Chaos"
    MAGIC_CIRCLE_AGAINST_EVIL = "Magic Circle against Evil"
    MAGIC_CIRCLE_AGAINST_GOOD = "Magic Circle against Good"
    MAGIC_CIRCLE_AGAINST_LAW = "Magic Circle against Law"
    MAGIC_VESTMENT = "Magic Vestment"
    MAGIC_WEAPON = "Magic Weapon"
    MAGIC_WEAPON_GREATER = "Magic Weapon (Greater)"
    MANTLE_OF_FAITH = "Mantle of Faith"
    MANTLE_OF_SPELL_RESISTANCE = "Mantle of Spell Resistance"
    MANUAL_OF_BODILY_HEALTH_PLUS_1 = "Manual of Bodily Health +1"
    MANUAL_OF_BODILY_HEALTH_PLUS_2 = "Manual of Bodily Health +2"
    MANUAL_OF_BODILY_HEALTH_PLUS_3 = "Manual of Bodily Health +3"
    MANUAL_OF_BODILY_HEALTH_PLUS_4 = "Manual of Bodily Health +4"
    MANUAL_OF_BODILY_HEALTH_PLUS_5 = "Manual of Bodily Health +5"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_1 = "Manual of Gainful Exercise +1"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_2 = "Manual of Gainful Exercise +2"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_3 = "Manual of Gainful Exercise +3"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_4 = "Manual of Gainful Exercise +4"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_5 = "Manual of Gainful Exercise +5"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_1 = "Manual of Quickness of Action +1"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_2 = "Manual of Quickness of Action +2"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_3 = "Manual of Quickness of Action +3"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_4 = "Manual of Quickness of Action +4"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_5 = "Manual of Quickness of Action +5"
    MARVELOUS_PIGMENTS = "Marvelous Pigments"
    MASK_OF_THE_SKULL = "Mask of the Skull"
    MATTOCK_OF_THE_TITANS = "Mattock of the Titans"
    MAUL_OF_THE_TITANS = "Maul of the Titans"
    MEDALLION_OF_THOUGHTS = "Medallion of Thoughts"
    MIGHTY_RAGE = "Mighty Rage"
    MIRROR_OF_LIFE_TRAPPING = "Mirror of Life Trapping"
    MIRROR_OF_MENTAL_PROWESS = "Mirror of Mental Prowess"
    MIRROR_OF_OPPOSITION = "Mirror of Opposition"
    MOMENT_OF_PRESCIENCE = "Moment of Prescience"
    MONKS_BELT = "Monk's Belt"
    NAUSEATED = "Nauseated"
    NECKLACE_OF_ADAPTATION = "Necklace of Adaptation"
    NECKLACE_OF_FIREBALLS_TYPE_I = "Necklace of Fireballs (Type I)"
    NECKLACE_OF_FIREBALLS_TYPE_II = "Necklace of Fireballs (Type II)"
    NECKLACE_OF_FIREBALLS_TYPE_III = "Necklace of Fireballs (Type III)"
    NECKLACE_OF_FIREBALLS_TYPE_IV = "Necklace of Fireballs (Type IV)"
    NECKLACE_OF_FIREBALLS_TYPE_V = "Necklace of Fireballs (Type V)"
    NECKLACE_OF_FIREBALLS_TYPE_VI = "Necklace of Fireballs (Type VI)"
    NECKLACE_OF_FIREBALLS_TYPE_VII = "Necklace of Fireballs (Type VII)"
    ORB_OF_STORMS = "Orb of Storms"
    OWLS_WISDOM = "Owl's Wisdom"
    PALADIN_DIVINE_GRACE = "Paladin divine_grace"
    PARALYZED = "Paralyzed"
    PEARL_OF_POWER_1ST_LEVEL = "Pearl of Power (1st Level)"
    PEARL_OF_POWER_2ND_LEVEL = "Pearl of Power (2nd Level)"
    PEARL_OF_POWER_3RD_LEVEL = "Pearl of Power (3rd Level)"
    PEARL_OF_POWER_4TH_LEVEL = "Pearl of Power (4th Level)"
    PEARL_OF_POWER_5TH_LEVEL = "Pearl of Power (5th Level)"
    PEARL_OF_POWER_6TH_LEVEL = "Pearl of Power (6th Level)"
    PEARL_OF_POWER_7TH_LEVEL = "Pearl of Power (7th Level)"
    PEARL_OF_POWER_8TH_LEVEL = "Pearl of Power (8th Level)"
    PEARL_OF_POWER_9TH_LEVEL = "Pearl of Power (9th Level)"
    PEARL_OF_POWER_TWO_SPELLS = "Pearl of Power (Two Spells)"
    PEARL_OF_THE_SIRINES = "Pearl of the Sirines"
    PERIAPT_OF_HEALTH = "Periapt of Health"
    PERIAPT_OF_PROOF_AGAINST_POISON = "Periapt of Proof against Poison"
    PERIAPT_OF_WISDOM_PLUS_2 = "Periapt of Wisdom +2"
    PERIAPT_OF_WISDOM_PLUS_4 = "Periapt of Wisdom +4"
    PERIAPT_OF_WISDOM_PLUS_6 = "Periapt of Wisdom +6"
    PERIAPT_OF_WOUND_CLOSURE = "Periapt of Wound Closure"
    PETRIFIED = "Petrified"
    PHYLACTERY_OF_FAITHFULNESS = "Phylactery of Faithfulness"
    PHYLACTERY_OF_UNDEAD_TURNING = "Phylactery of Undead Turning"
    PIPES_OF_HAUNTING = "Pipes of Haunting"
    PIPES_OF_PAIN = "Pipes of Pain"
    PIPES_OF_SOUNDING = "Pipes of Sounding"
    PIPES_OF_THE_SEWERS = "Pipes of the Sewers"
    PORTABLE_HOLE = "Portable Hole"
    PRAYER = "Prayer"
    PRONE = "Prone"
    PROTECTION_FROM_CHAOS = "Protection from Chaos"
    PROTECTION_FROM_EVIL = "Protection from Evil"
    PROTECTION_FROM_GOOD = "Protection from Good"
    PROTECTION_FROM_LAW = "Protection from Law"
    RAGE = "Rage"
    RAY_OF_ENFEEBLEMENT = "Ray of Enfeeblement"
    REDUCE_PERSON = "Reduce Person"
    RESISTANCE = "Resistance"
    RESTORATIVE_OINTMENT = "Restorative Ointment"
    RIGHTEOUS_MIGHT = "Righteous Might"
    RING_GATES = "Ring Gates"
    RING_OF_CHAMELEON_POWER = "Ring of Chameleon Power"
    RING_OF_CLIMBING = "Ring of Climbing"
    RING_OF_CLIMBING_IMPROVED = "Ring of Climbing, Improved"
    RING_OF_FORCE_SHIELD = "Ring of Force Shield"
    RING_OF_JUMPING = "Ring of Jumping"
    RING_OF_JUMPING_IMPROVED = "Ring of Jumping, Improved"
    RING_OF_PROTECTION_PLUS_1 = "Ring of Protection +1"
    RING_OF_PROTECTION_PLUS_2 = "Ring of Protection +2"
    RING_OF_PROTECTION_PLUS_3 = "Ring of Protection +3"
    RING_OF_PROTECTION_PLUS_4 = "Ring of Protection +4"
    RING_OF_PROTECTION_PLUS_5 = "Ring of Protection +5"
    RING_OF_SWIMMING = "Ring of Swimming"
    RING_OF_SWIMMING_IMPROVED = "Ring of Swimming, Improved"
    ROBE_OF_BLENDING = "Robe of Blending"
    ROBE_OF_BONES = "Robe of Bones"
    ROBE_OF_EYES = "Robe of Eyes"
    ROBE_OF_SCINTILLATING_COLORS = "Robe of Scintillating Colors"
    ROBE_OF_STARS = "Robe of Stars"
    ROBE_OF_THE_ARCHMAGI = "Robe of the Archmagi"
    ROBE_OF_USEFUL_ITEMS = "Robe of Useful Items"
    ROPE_OF_CLIMBING = "Rope of Climbing"
    ROPE_OF_ENTANGLEMENT = "Rope of Entanglement"
    SALVE_OF_SLIPPERINESS = "Salve of Slipperiness"
    SCABBARD_OF_KEEN_EDGES = "Scabbard of Keen Edges"
    SCARAB_OF_PROTECTION = "Scarab of Protection"
    SHIELD = "Shield"
    SHIELD_OF_FAITH = "Shield of Faith"
    SHIELD_OF_LAW = "Shield of Law"
    SHROUDS_OF_DISINTEGRATION = "Shrouds of Disintegration"
    SILVERSHEEN = "Silversheen"
    SLIPPERS_OF_SPIDER_CLIMBING = "Slippers of Spider Climbing"
    SMITE_EVIL = "Smite Evil"
    SOVEREIGN_GLUE = "Sovereign Glue"
    SPELL_RESISTANCE = "Spell Resistance"
    STAGGERED = "Staggered"
    STONE_HORSE_COURSER = "Stone Horse (Courser)"
    STONE_HORSE_DESTRIER = "Stone Horse (Destrier)"
    STONE_OF_ALARM = "Stone of Alarm"
    STONE_OF_CONTROLLING_EARTH_ELEMENTALS = (
        "Stone of Controlling Earth Elementals"
    )
    STONE_OF_GOOD_LUCK_LUCKSTONE = "Stone of Good Luck (Luckstone)"
    STONE_SALVE = "Stone Salve"
    STRAND_OF_PRAYER_BEADS = "Strand of Prayer Beads"
    STRAND_OF_PRAYER_BEADS_GREATER = "Strand of Prayer Beads (Greater)"
    STRAND_OF_PRAYER_BEADS_LESSER = "Strand of Prayer Beads (Lesser)"
    SUSTAINING_SPOON = "Sustaining Spoon"
    TOME_OF_CLEAR_THOUGHT_PLUS_1 = "Tome of Clear Thought +1"
    TOME_OF_CLEAR_THOUGHT_PLUS_2 = "Tome of Clear Thought +2"
    TOME_OF_CLEAR_THOUGHT_PLUS_3 = "Tome of Clear Thought +3"
    TOME_OF_CLEAR_THOUGHT_PLUS_4 = "Tome of Clear Thought +4"
    TOME_OF_CLEAR_THOUGHT_PLUS_5 = "Tome of Clear Thought +5"
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_1 = (
        "Tome of Leadership and Influence +1"
    )
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_2 = (
        "Tome of Leadership and Influence +2"
    )
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_3 = (
        "Tome of Leadership and Influence +3"
    )
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_4 = (
        "Tome of Leadership and Influence +4"
    )
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_5 = (
        "Tome of Leadership and Influence +5"
    )
    TOME_OF_UNDERSTANDING_PLUS_1 = "Tome of Understanding +1"
    TOME_OF_UNDERSTANDING_PLUS_2 = "Tome of Understanding +2"
    TOME_OF_UNDERSTANDING_PLUS_3 = "Tome of Understanding +3"
    TOME_OF_UNDERSTANDING_PLUS_4 = "Tome of Understanding +4"
    TOME_OF_UNDERSTANDING_PLUS_5 = "Tome of Understanding +5"
    TOUCH_OF_IDIOCY = "Touch of Idiocy"
    TRANSFORMATION = "Transformation"
    TURNED = "Turned"
    UNGUENT_OF_TIMELESSNESS = "Unguent of Timelessness"
    UNHOLY_AURA = "Unholy Aura"
    UNIVERSAL_SOLVENT = "Universal Solvent"
    VEST_OF_ESCAPE = "Vest of Escape"
    VEST_OF_RESISTANCE_PLUS_1 = "Vest of Resistance +1"
    VEST_OF_RESISTANCE_PLUS_2 = "Vest of Resistance +2"
    VEST_OF_RESISTANCE_PLUS_3 = "Vest of Resistance +3"
    VEST_OF_RESISTANCE_PLUS_4 = "Vest of Resistance +4"
    VEST_OF_RESISTANCE_PLUS_5 = "Vest of Resistance +5"
    VIRTUE = "Virtue"
    WELL_OF_MANY_WORLDS = "Well of Many Worlds"
    WIND_FAN = "Wind Fan"
    WINGED_BOOTS = "Winged Boots"
    WINGS_OF_FLYING = "Wings of Flying"
