"""
buffs.py
SRD core buffs (spells, feats, conditions,
class features, etc).

Buffs are temporary toggleable effects.
Magic items are NOT buffs —
see engine.equipment.equip_item.
"""

from __future__ import annotations

from enum import StrEnum


class KnownCoreBuff(StrEnum):
    AID = "Aid"
    BARBARIAN_FAST_MOVEMENT = "Barbarian fast_movement"
    BARBARIAN_RAGE = "Barbarian Rage"
    BARKSKIN = "Barkskin"
    BEARS_ENDURANCE = "Bear's Endurance"
    BLACKGUARD_DARK_BLESSING = "Blackguard dark_blessing"
    BLESS = "Bless"
    BLESS_WEAPON = "Bless Weapon"
    BULLS_STRENGTH = "Bull's Strength"
    CATS_GRACE = "Cat's Grace"
    CLOAK_OF_CHAOS = "Cloak of Chaos"
    CONFUSED = "Confused"
    COWERING = "Cowering"
    DAZED = "Dazed"
    DEAFENED = "Deafened"
    DEFENSIVE_STANCE = "Defensive Stance"
    DISABLED = "Disabled"
    DIVINE_FAVOR = "Divine Favor"
    DIVINE_POWER = "Divine Power"
    DODGE = "Dodge"
    DOOM = "Doom"
    DRAGON_DISCIPLE_NATURAL_ARMOR_1 = "Dragon Disciple natural_armor_1"
    DRAGON_DISCIPLE_NATURAL_ARMOR_4 = "Dragon Disciple natural_armor_4"
    DRAGON_DISCIPLE_NATURAL_ARMOR_7 = "Dragon Disciple natural_armor_7"
    DRAGON_DISCIPLE_STR_INCREASE_2 = "Dragon Disciple str_increase_2"
    DRAGON_DISCIPLE_STR_INCREASE_4 = "Dragon Disciple str_increase_4"
    DUELIST_CANNY_DEFENSE = "Duelist canny_defense"
    DUELIST_GRACE = "Duelist grace"
    DUELIST_IMPROVED_REACTION = "Duelist improved_reaction"
    DYING = "Dying"
    EAGLES_SPLENDOR = "Eagle's Splendor"
    ENERGY_DRAINED = "Energy Drained"
    ENLARGE_PERSON = "Enlarge Person"
    EXPEDITIOUS_RETREAT = "Expeditious Retreat"
    FALSE_LIFE = "False Life"
    FASCINATED = "Fascinated"
    FAVORED_ENEMY_PLUS_2 = "Favored Enemy +2"
    FAVORED_ENEMY_PLUS_4 = "Favored Enemy +4"
    FAVORED_ENEMY_PLUS_6 = "Favored Enemy +6"
    FLAT_FOOTED = "Flat-Footed"
    FLURRY_OF_BLOWS = "Flurry of Blows"
    FORESIGHT = "Foresight"
    FOXS_CUNNING = "Fox's Cunning"
    GOOD_HOPE = "Good Hope"
    GRAPPLING = "Grappling"
    GREATER_RAGE = "Greater Rage"
    GUIDANCE = "Guidance"
    HASTE = "Haste"
    HELPLESS = "Helpless"
    HEROISM = "Heroism"
    HEROISM_GREATER = "Heroism (Greater)"
    HOLY_AURA = "Holy Aura"
    INSPIRE_COURAGE_PLUS_1 = "Inspire Courage +1"
    INSPIRE_COURAGE_PLUS_2 = "Inspire Courage +2"
    INSPIRE_COURAGE_PLUS_3 = "Inspire Courage +3"
    INSPIRE_COURAGE_PLUS_4 = "Inspire Courage +4"
    INSPIRE_GREATNESS = "Inspire Greatness"
    INVISIBILITY = "Invisibility"
    INVISIBLE = "Invisible"
    IRON_BODY = "Iron Body"
    JUMP = "Jump"
    LONGSTRIDER = "Longstrider"
    MAGE_ARMOR = "Mage Armor"
    MAGIC_CIRCLE_AGAINST_CHAOS = "Magic Circle against Chaos"
    MAGIC_CIRCLE_AGAINST_EVIL = "Magic Circle against Evil"
    MAGIC_CIRCLE_AGAINST_GOOD = "Magic Circle against Good"
    MAGIC_CIRCLE_AGAINST_LAW = "Magic Circle against Law"
    MAGIC_VESTMENT = "Magic Vestment"
    MAGIC_WEAPON = "Magic Weapon"
    MAGIC_WEAPON_GREATER = "Magic Weapon (Greater)"
    MIGHTY_RAGE = "Mighty Rage"
    MOMENT_OF_PRESCIENCE = "Moment of Prescience"
    NAUSEATED = "Nauseated"
    OWLS_WISDOM = "Owl's Wisdom"
    PALADIN_DIVINE_GRACE = "Paladin divine_grace"
    PARALYZED = "Paralyzed"
    PETRIFIED = "Petrified"
    PRAYER = "Prayer"
    PRONE = "Prone"
    PROTECTION_FROM_CHAOS = "Protection from Chaos"
    PROTECTION_FROM_EVIL = "Protection from Evil"
    PROTECTION_FROM_GOOD = "Protection from Good"
    PROTECTION_FROM_LAW = "Protection from Law"
    RAGE = "Rage"
    RAY_OF_ENFEEBLEMENT = "Ray of Enfeeblement"
    REDUCE_PERSON = "Reduce Person"
    RESISTANCE = "Resistance"
    RIGHTEOUS_MIGHT = "Righteous Might"
    SHIELD = "Shield"
    SHIELD_OF_FAITH = "Shield of Faith"
    SHIELD_OF_LAW = "Shield of Law"
    SMITE_EVIL = "Smite Evil"
    SPELL_RESISTANCE = "Spell Resistance"
    STAGGERED = "Staggered"
    TOUCH_OF_IDIOCY = "Touch of Idiocy"
    TRANSFORMATION = "Transformation"
    TURNED = "Turned"
    UNHOLY_AURA = "Unholy Aura"
    VIRTUE = "Virtue"
