"""
magic_items.py
SRD core magic items.
"""

from __future__ import annotations

from enum import StrEnum


class KnownCoreMagicItem(StrEnum):
    HEADBAND_OF_INTELLECT_PLUS_2 = "Headband of Intellect +2"
    HEADBAND_OF_INTELLECT_PLUS_4 = "Headband of Intellect +4"
    HEADBAND_OF_INTELLECT_PLUS_6 = "Headband of Intellect +6"
    HELM_OF_BRILLIANCE = "Helm of Brilliance"
    EYES_OF_THE_EAGLE = "Eyes of the Eagle"
    GOGGLES_OF_MINUTE_SEEING = "Goggles of Minute Seeing"
    AMULET_OF_HEALTH_PLUS_2 = "Amulet of Health +2"
    AMULET_OF_HEALTH_PLUS_4 = "Amulet of Health +4"
    AMULET_OF_HEALTH_PLUS_6 = "Amulet of Health +6"
    AMULET_OF_MIGHTY_FISTS_PLUS_1 = "Amulet of Mighty Fists +1"
    AMULET_OF_MIGHTY_FISTS_PLUS_2 = "Amulet of Mighty Fists +2"
    AMULET_OF_MIGHTY_FISTS_PLUS_3 = "Amulet of Mighty Fists +3"
    AMULET_OF_MIGHTY_FISTS_PLUS_4 = "Amulet of Mighty Fists +4"
    AMULET_OF_MIGHTY_FISTS_PLUS_5 = "Amulet of Mighty Fists +5"
    AMULET_OF_NATURAL_ARMOR_PLUS_1 = "Amulet of Natural Armor +1"
    AMULET_OF_NATURAL_ARMOR_PLUS_2 = "Amulet of Natural Armor +2"
    AMULET_OF_NATURAL_ARMOR_PLUS_3 = "Amulet of Natural Armor +3"
    AMULET_OF_NATURAL_ARMOR_PLUS_4 = "Amulet of Natural Armor +4"
    AMULET_OF_NATURAL_ARMOR_PLUS_5 = "Amulet of Natural Armor +5"
    PERIAPT_OF_WISDOM_PLUS_2 = "Periapt of Wisdom +2"
    PERIAPT_OF_WISDOM_PLUS_4 = "Periapt of Wisdom +4"
    PERIAPT_OF_WISDOM_PLUS_6 = "Periapt of Wisdom +6"
    SCARAB_OF_PROTECTION = "Scarab of Protection"
    CLOAK_OF_CHARISMA_PLUS_2 = "Cloak of Charisma +2"
    CLOAK_OF_CHARISMA_PLUS_4 = "Cloak of Charisma +4"
    CLOAK_OF_CHARISMA_PLUS_6 = "Cloak of Charisma +6"
    CLOAK_OF_ELVENKIND = "Cloak of Elvenkind"
    CLOAK_OF_RESISTANCE_PLUS_1 = "Cloak of Resistance +1"
    CLOAK_OF_RESISTANCE_PLUS_2 = "Cloak of Resistance +2"
    CLOAK_OF_RESISTANCE_PLUS_3 = "Cloak of Resistance +3"
    CLOAK_OF_RESISTANCE_PLUS_4 = "Cloak of Resistance +4"
    CLOAK_OF_RESISTANCE_PLUS_5 = "Cloak of Resistance +5"
    ROBE_OF_STARS = "Robe of Stars"
    ROBE_OF_THE_ARCHMAGI = "Robe of the Archmagi"
    MONKS_BELT = "Monk's Belt"
    VEST_OF_ESCAPE = "Vest of Escape"
    VEST_OF_RESISTANCE_PLUS_1 = "Vest of Resistance +1"
    VEST_OF_RESISTANCE_PLUS_2 = "Vest of Resistance +2"
    VEST_OF_RESISTANCE_PLUS_3 = "Vest of Resistance +3"
    VEST_OF_RESISTANCE_PLUS_4 = "Vest of Resistance +4"
    VEST_OF_RESISTANCE_PLUS_5 = "Vest of Resistance +5"
    BRACERS_OF_ARCHERY_GREATER = "Bracers of Archery (Greater)"
    BRACERS_OF_ARCHERY_LESSER = "Bracers of Archery (Lesser)"
    BRACERS_OF_ARMOR_PLUS_1 = "Bracers of Armor +1"
    BRACERS_OF_ARMOR_PLUS_2 = "Bracers of Armor +2"
    BRACERS_OF_ARMOR_PLUS_3 = "Bracers of Armor +3"
    BRACERS_OF_ARMOR_PLUS_4 = "Bracers of Armor +4"
    BRACERS_OF_ARMOR_PLUS_5 = "Bracers of Armor +5"
    BRACERS_OF_ARMOR_PLUS_6 = "Bracers of Armor +6"
    BRACERS_OF_ARMOR_PLUS_7 = "Bracers of Armor +7"
    BRACERS_OF_ARMOR_PLUS_8 = "Bracers of Armor +8"
    GAUNTLETS_OF_OGRE_POWER = "Gauntlets of Ogre Power"
    GLOVES_OF_DEXTERITY_PLUS_2 = "Gloves of Dexterity +2"
    GLOVES_OF_DEXTERITY_PLUS_4 = "Gloves of Dexterity +4"
    GLOVES_OF_DEXTERITY_PLUS_6 = "Gloves of Dexterity +6"
    RING_OF_CHAMELEON_POWER = "Ring of Chameleon Power"
    RING_OF_CLIMBING = "Ring of Climbing"
    RING_OF_CLIMBING_IMPROVED = "Ring of Climbing, Improved"
    RING_OF_FORCE_SHIELD = "Ring of Force Shield"
    RING_OF_JUMPING = "Ring of Jumping"
    RING_OF_JUMPING_IMPROVED = "Ring of Jumping, Improved"
    RING_OF_PROTECTION_PLUS_1 = "Ring of Protection +1"
    RING_OF_PROTECTION_PLUS_2 = "Ring of Protection +2"
    RING_OF_PROTECTION_PLUS_3 = "Ring of Protection +3"
    RING_OF_PROTECTION_PLUS_4 = "Ring of Protection +4"
    RING_OF_PROTECTION_PLUS_5 = "Ring of Protection +5"
    RING_OF_SWIMMING = "Ring of Swimming"
    RING_OF_SWIMMING_IMPROVED = "Ring of Swimming, Improved"
    BELT_OF_DWARVENKIND = "Belt of Dwarvenkind"
    BELT_OF_GIANT_STRENGTH_PLUS_2 = "Belt of Giant Strength +2"
    BELT_OF_GIANT_STRENGTH_PLUS_4 = "Belt of Giant Strength +4"
    BELT_OF_GIANT_STRENGTH_PLUS_6 = "Belt of Giant Strength +6"
    BOOTS_OF_ELVENKIND = "Boots of Elvenkind"
    BOOTS_OF_SPEED = "Boots of Speed"
    BOOTS_OF_STRIDING_AND_SPRINGING = "Boots of Striding and Springing"
    CANDLE_OF_INVOCATION = "Candle of Invocation"
    CIRCLET_OF_PERSUASION = "Circlet of Persuasion"
    IOUN_STONE_DEEP_RED_SPHERE = "Ioun Stone (Deep Red Sphere)"
    IOUN_STONE_DUSTY_ROSE_PRISM = "Ioun Stone (Dusty Rose Prism)"
    IOUN_STONE_INCANDESCENT_BLUE = "Ioun Stone (Incandescent Blue)"
    IOUN_STONE_PALE_BLUE_RHOMBOID = "Ioun Stone (Pale Blue Rhomboid)"
    IOUN_STONE_PALE_GREEN_PRISM = "Ioun Stone (Pale Green Prism)"
    IOUN_STONE_PINK_AND_GREEN = "Ioun Stone (Pink and Green)"
    IOUN_STONE_PINK_RHOMBOID = "Ioun Stone (Pink Rhomboid)"
    IOUN_STONE_SCARLET_AND_BLUE = "Ioun Stone (Scarlet and Blue)"
    MANTLE_OF_SPELL_RESISTANCE = "Mantle of Spell Resistance"
    STONE_OF_GOOD_LUCK_LUCKSTONE = "Stone of Good Luck (Luckstone)"
    MANUAL_OF_BODILY_HEALTH_PLUS_1 = "Manual of Bodily Health +1"
    MANUAL_OF_GAINFUL_EXERCISE_PLUS_1 = "Manual of Gainful Exercise +1"
    MANUAL_OF_QUICKNESS_OF_ACTION_PLUS_1 = "Manual of Quickness of Action +1"
    TOME_OF_CLEAR_THOUGHT_PLUS_1 = "Tome of Clear Thought +1"
    TOME_OF_LEADERSHIP_AND_INFLUENCE_PLUS_1 = (
        "Tome of Leadership and Influence +1"
    )
    TOME_OF_UNDERSTANDING_PLUS_1 = "Tome of Understanding +1"
