"""
rules/core/pool_keys.py
------------------------
Closed set of BonusPool identifiers used by the engine.

AUTO-GENERATED by _gen_pool_keys.py. Edit stats.yaml or
skills.yaml and rerun ``uv run check-pool-keys --fix``.
"""

from __future__ import annotations

from enum import StrEnum


class PoolKey(StrEnum):
    STR_SCORE = "str_score"
    DEX_SCORE = "dex_score"
    CON_SCORE = "con_score"
    INT_SCORE = "int_score"
    WIS_SCORE = "wis_score"
    CHA_SCORE = "cha_score"
    BAB_MISC = "bab_misc"
    FORT_SAVE = "fort_save"
    REF_SAVE = "ref_save"
    WILL_SAVE = "will_save"
    AC = "ac"
    INITIATIVE = "initiative"
    SPEED = "speed"
    HP_BONUS = "hp_bonus"
    SR = "sr"
    ATTACK_MELEE = "attack_melee"
    ATTACK_ALL = "attack_all"
    ATTACK_RANGED = "attack_ranged"
    DAMAGE_MELEE = "damage_melee"
    DAMAGE_ALL = "damage_all"
    GRAPPLE = "grapple"
    DAMAGE_RANGED = "damage_ranged"
    SKILL_APPRAISE = "skill_appraise"
    SKILL_BALANCE = "skill_balance"
    SKILL_BLUFF = "skill_bluff"
    SKILL_CLIMB = "skill_climb"
    SKILL_CONCENTRATION = "skill_concentration"
    SKILL_CRAFT = "skill_craft"
    SKILL_DECIPHER_SCRIPT = "skill_decipher_script"
    SKILL_DIPLOMACY = "skill_diplomacy"
    SKILL_DISABLE_DEVICE = "skill_disable_device"
    SKILL_DISGUISE = "skill_disguise"
    SKILL_ESCAPE_ARTIST = "skill_escape_artist"
    SKILL_FORGERY = "skill_forgery"
    SKILL_GATHER_INFORMATION = "skill_gather_information"
    SKILL_HANDLE_ANIMAL = "skill_handle_animal"
    SKILL_HEAL = "skill_heal"
    SKILL_HIDE = "skill_hide"
    SKILL_INTIMIDATE = "skill_intimidate"
    SKILL_JUMP = "skill_jump"
    SKILL_KNOWLEDGE_ARCANA = "skill_knowledge_arcana"
    SKILL_KNOWLEDGE_ARCHITECTURE_AND_ENGINEERING = (
        "skill_knowledge_architecture_and_engineering"
    )
    SKILL_KNOWLEDGE_DUNGEONEERING = "skill_knowledge_dungeoneering"
    SKILL_KNOWLEDGE_GEOGRAPHY = "skill_knowledge_geography"
    SKILL_KNOWLEDGE_HISTORY = "skill_knowledge_history"
    SKILL_KNOWLEDGE_LOCAL = "skill_knowledge_local"
    SKILL_KNOWLEDGE_NATURE = "skill_knowledge_nature"
    SKILL_KNOWLEDGE_NOBILITY_AND_ROYALTY = (
        "skill_knowledge_nobility_and_royalty"
    )
    SKILL_KNOWLEDGE_RELIGION = "skill_knowledge_religion"
    SKILL_KNOWLEDGE_THE_PLANES = "skill_knowledge_the_planes"
    SKILL_LISTEN = "skill_listen"
    SKILL_MOVE_SILENTLY = "skill_move_silently"
    SKILL_OPEN_LOCK = "skill_open_lock"
    SKILL_PERFORM = "skill_perform"
    SKILL_PERFORM_DANCE = "skill_perform_dance"
    SKILL_PROFESSION = "skill_profession"
    SKILL_PROFESSION_SOLDIER = "skill_profession_soldier"
    SKILL_RIDE = "skill_ride"
    SKILL_SEARCH = "skill_search"
    SKILL_SENSE_MOTIVE = "skill_sense_motive"
    SKILL_SLEIGHT_OF_HAND = "skill_sleight_of_hand"
    SKILL_SPEAK_LANGUAGE = "skill_speak_language"
    SKILL_SPELLCRAFT = "skill_spellcraft"
    SKILL_SPOT = "skill_spot"
    SKILL_SURVIVAL = "skill_survival"
    SKILL_SWIM = "skill_swim"
    SKILL_TUMBLE = "skill_tumble"
    SKILL_USE_MAGIC_DEVICE = "skill_use_magic_device"
    SKILL_USE_ROPE = "skill_use_rope"


_SKILL_NAME_TO_POOL_KEY: dict[str, PoolKey] = {
    "Appraise": PoolKey.SKILL_APPRAISE,
    "Balance": PoolKey.SKILL_BALANCE,
    "Bluff": PoolKey.SKILL_BLUFF,
    "Climb": PoolKey.SKILL_CLIMB,
    "Concentration": PoolKey.SKILL_CONCENTRATION,
    "Craft": PoolKey.SKILL_CRAFT,
    "Decipher Script": PoolKey.SKILL_DECIPHER_SCRIPT,
    "Diplomacy": PoolKey.SKILL_DIPLOMACY,
    "Disable Device": PoolKey.SKILL_DISABLE_DEVICE,
    "Disguise": PoolKey.SKILL_DISGUISE,
    "Escape Artist": PoolKey.SKILL_ESCAPE_ARTIST,
    "Forgery": PoolKey.SKILL_FORGERY,
    "Gather Information": PoolKey.SKILL_GATHER_INFORMATION,
    "Handle Animal": PoolKey.SKILL_HANDLE_ANIMAL,
    "Heal": PoolKey.SKILL_HEAL,
    "Hide": PoolKey.SKILL_HIDE,
    "Intimidate": PoolKey.SKILL_INTIMIDATE,
    "Jump": PoolKey.SKILL_JUMP,
    "Knowledge (Arcana)": PoolKey.SKILL_KNOWLEDGE_ARCANA,
    "Knowledge (Architecture and Engineering)": (
        PoolKey.SKILL_KNOWLEDGE_ARCHITECTURE_AND_ENGINEERING
    ),
    "Knowledge (Dungeoneering)": PoolKey.SKILL_KNOWLEDGE_DUNGEONEERING,
    "Knowledge (Geography)": PoolKey.SKILL_KNOWLEDGE_GEOGRAPHY,
    "Knowledge (History)": PoolKey.SKILL_KNOWLEDGE_HISTORY,
    "Knowledge (Local)": PoolKey.SKILL_KNOWLEDGE_LOCAL,
    "Knowledge (Nature)": PoolKey.SKILL_KNOWLEDGE_NATURE,
    "Knowledge (Nobility and Royalty)": (
        PoolKey.SKILL_KNOWLEDGE_NOBILITY_AND_ROYALTY
    ),
    "Knowledge (Religion)": PoolKey.SKILL_KNOWLEDGE_RELIGION,
    "Knowledge (The Planes)": PoolKey.SKILL_KNOWLEDGE_THE_PLANES,
    "Listen": PoolKey.SKILL_LISTEN,
    "Move Silently": PoolKey.SKILL_MOVE_SILENTLY,
    "Open Lock": PoolKey.SKILL_OPEN_LOCK,
    "Perform": PoolKey.SKILL_PERFORM,
    "Perform (Dance)": PoolKey.SKILL_PERFORM_DANCE,
    "Profession": PoolKey.SKILL_PROFESSION,
    "Profession (Soldier)": PoolKey.SKILL_PROFESSION_SOLDIER,
    "Ride": PoolKey.SKILL_RIDE,
    "Search": PoolKey.SKILL_SEARCH,
    "Sense Motive": PoolKey.SKILL_SENSE_MOTIVE,
    "Sleight of Hand": PoolKey.SKILL_SLEIGHT_OF_HAND,
    "Speak Language": PoolKey.SKILL_SPEAK_LANGUAGE,
    "Spellcraft": PoolKey.SKILL_SPELLCRAFT,
    "Spot": PoolKey.SKILL_SPOT,
    "Survival": PoolKey.SKILL_SURVIVAL,
    "Swim": PoolKey.SKILL_SWIM,
    "Tumble": PoolKey.SKILL_TUMBLE,
    "Use Magic Device": PoolKey.SKILL_USE_MAGIC_DEVICE,
    "Use Rope": PoolKey.SKILL_USE_ROPE,
}


def pool_key_for_skill(name: str) -> PoolKey:
    """Return the PoolKey that backs a skill named ``name``."""
    try:
        return _SKILL_NAME_TO_POOL_KEY[name]
    except KeyError as exc:
        msg = f"No PoolKey registered for skill {name!r}"
        raise KeyError(msg) from exc
