"""
pool_keys.py
Closed set of BonusPool identifiers used by the engine.

AUTO-GENERATED by _gen_pool_keys.py.
Edit the matching YAML and rerun
``uv run check-pool-keys --fix``.
"""

from enum import StrEnum

from heroforge.rules.combine_str_enum import combine
from heroforge.rules.core.skills import KnownCoreSkill


class _StatPoolKey(StrEnum):
    STR_SCORE = "str_score"
    DEX_SCORE = "dex_score"
    CON_SCORE = "con_score"
    INT_SCORE = "int_score"
    WIS_SCORE = "wis_score"
    CHA_SCORE = "cha_score"
    BAB_MISC = "bab_misc"
    FORT_SAVE = "fort_save"
    REF_SAVE = "ref_save"
    WILL_SAVE = "will_save"
    AC = "ac"
    INITIATIVE = "initiative"
    SPEED = "speed"
    HP_BONUS = "hp_bonus"
    SR = "sr"
    ATTACK_MELEE = "attack_melee"
    ATTACK_ALL = "attack_all"
    ATTACK_RANGED = "attack_ranged"
    DAMAGE_MELEE = "damage_melee"
    DAMAGE_ALL = "damage_all"
    EFFECTIVE_MONK_LEVEL_AC = "effective_monk_level_ac"
    GRAPPLE = "grapple"
    DAMAGE_RANGED = "damage_ranged"


_SkillPoolKey = StrEnum(
    "SkillPoolKey",
    {
        f"SKILL_{skill.name}": f"skill_{skill.name.lower()}"
        for skill in KnownCoreSkill
    },
)


PoolKey = combine("PoolKey", _StatPoolKey, _SkillPoolKey)
