"""
skills.py
SRD core skills.
"""

from __future__ import annotations

from enum import StrEnum


class KnownCoreSkill(StrEnum):
    APPRAISE = "Appraise"
    BALANCE = "Balance"
    BLUFF = "Bluff"
    CLIMB = "Climb"
    CONCENTRATION = "Concentration"
    CRAFT = "Craft"
    CRAFT_CONSPIRACY = "Craft (Conspiracy)"
    DECIPHER_SCRIPT = "Decipher Script"
    DIPLOMACY = "Diplomacy"
    DISABLE_DEVICE = "Disable Device"
    DISGUISE = "Disguise"
    ESCAPE_ARTIST = "Escape Artist"
    FORGERY = "Forgery"
    GATHER_INFORMATION = "Gather Information"
    HANDLE_ANIMAL = "Handle Animal"
    HEAL = "Heal"
    HIDE = "Hide"
    INTIMIDATE = "Intimidate"
    JUMP = "Jump"
    KNOWLEDGE_ARCANA = "Knowledge (Arcana)"
    KNOWLEDGE_ARCHITECTURE_AND_ENGINEERING = (
        "Knowledge (Architecture and Engineering)"
    )
    KNOWLEDGE_DUNGEONEERING = "Knowledge (Dungeoneering)"
    KNOWLEDGE_GEOGRAPHY = "Knowledge (Geography)"
    KNOWLEDGE_HISTORY = "Knowledge (History)"
    KNOWLEDGE_LOCAL = "Knowledge (Local)"
    KNOWLEDGE_LOCAL_CORE = "Knowledge (Local Core)"
    KNOWLEDGE_LOCAL_IUZ = "Knowledge (Local Iuz)"
    KNOWLEDGE_LOCAL_VTF = "Knowledge (Local VTF)"
    KNOWLEDGE_NATURE = "Knowledge (Nature)"
    KNOWLEDGE_NOBILITY_AND_ROYALTY = "Knowledge (Nobility and Royalty)"
    KNOWLEDGE_RELIGION = "Knowledge (Religion)"
    KNOWLEDGE_THE_PLANES = "Knowledge (The Planes)"
    LISTEN = "Listen"
    MOVE_SILENTLY = "Move Silently"
    OPEN_LOCK = "Open Lock"
    PERFORM = "Perform"
    PERFORM_DANCE = "Perform (Dance)"
    PROFESSION = "Profession"
    PROFESSION_SOLDIER = "Profession (Soldier)"
    RIDE = "Ride"
    SEARCH = "Search"
    SENSE_MOTIVE = "Sense Motive"
    SLEIGHT_OF_HAND = "Sleight of Hand"
    SPEAK_LANGUAGE = "Speak Language"
    SPELLCRAFT = "Spellcraft"
    SPOT = "Spot"
    SURVIVAL = "Survival"
    SWIM = "Swim"
    TUMBLE = "Tumble"
    USE_MAGIC_DEVICE = "Use Magic Device"
    USE_ROPE = "Use Rope"
