"""
weapons.py
SRD core weapons.
"""

from __future__ import annotations

from enum import StrEnum


class KnownCoreWeapon(StrEnum):
    GAUNTLET = "Gauntlet"
    UNARMED_STRIKE = "Unarmed Strike"
    DAGGER = "Dagger"
    PUNCHING_DAGGER = "Punching Dagger"
    SPIKED_GAUNTLET = "Spiked Gauntlet"
    LIGHT_MACE = "Light Mace"
    SICKLE = "Sickle"
    CLUB = "Club"
    HEAVY_MACE = "Heavy Mace"
    MORNINGSTAR = "Morningstar"
    SHORTSPEAR = "Shortspear"
    LONGSPEAR = "Longspear"
    QUARTERSTAFF = "Quarterstaff"
    SPEAR = "Spear"
    HEAVY_CROSSBOW = "Heavy Crossbow"
    LIGHT_CROSSBOW = "Light Crossbow"
    DART = "Dart"
    JAVELIN = "Javelin"
    SLING = "Sling"
    THROWING_AXE = "Throwing Axe"
    LIGHT_HAMMER = "Light Hammer"
    HANDAXE = "Handaxe"
    KUKRI = "Kukri"
    LIGHT_PICK = "Light Pick"
    SAP = "Sap"
    SHORT_SWORD = "Short Sword"
    BATTLEAXE = "Battleaxe"
    FLAIL = "Flail"
    LONGSWORD = "Longsword"
    HEAVY_PICK = "Heavy Pick"
    RAPIER = "Rapier"
    SCIMITAR = "Scimitar"
    TRIDENT = "Trident"
    WARHAMMER = "Warhammer"
    FALCHION = "Falchion"
    GLAIVE = "Glaive"
    GREATAXE = "Greataxe"
    GREATCLUB = "Greatclub"
    HEAVY_FLAIL = "Heavy Flail"
    GREATSWORD = "Greatsword"
    GUISARME = "Guisarme"
    HALBERD = "Halberd"
    LANCE = "Lance"
    RANSEUR = "Ranseur"
    SCYTHE = "Scythe"
    LONGBOW = "Longbow"
    COMPOSITE_LONGBOW = "Composite Longbow"
    SHORTBOW = "Shortbow"
    COMPOSITE_SHORTBOW = "Composite Shortbow"
    KAMA = "Kama"
    NUNCHAKU = "Nunchaku"
    SAI = "Sai"
    SIANGHAM = "Siangham"
    BASTARD_SWORD = "Bastard Sword"
    DWARVEN_WARAXE = "Dwarven Waraxe"
    WHIP = "Whip"
    SPIKED_CHAIN = "Spiked Chain"
    HAND_CROSSBOW = "Hand Crossbow"
    REPEATING_HEAVY_CROSSBOW = "Repeating Heavy Crossbow"
    REPEATING_LIGHT_CROSSBOW = "Repeating Light Crossbow"
    NET = "Net"
    SHURIKEN = "Shuriken"
    BOLAS = "Bolas"
