"""
magic_items.py
Magic items from Races Of Stone.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownRacesOfStoneMagicItem(StrEnum):
    EARTHSILK_ROPE = "Earthsilk Rope"
