"""
magic_items.py
Magic items from Miniatures Handbook.

AUTO-GENERATED by _gen_magic_item_enums.py.
Edit the matching YAML and rerun
``uv run check-magic-items --fix``.
"""

from enum import StrEnum


class KnownMiniaturesHandbookMagicItem(StrEnum):
    BELT_OF_MAGNIFICENCE_PLUS_2 = "Belt of Magnificence +2"
    BELT_OF_MAGNIFICENCE_PLUS_4 = "Belt of Magnificence +4"
    BELT_OF_MAGNIFICENCE_PLUS_6 = "Belt of Magnificence +6"
