"""
_gen_magic_item_enums.py
-------------------------
Keep magic-item StrEnum Python files in sync with
their YAML sources.

Usage:
    uv run check-magic-items          # exit 1 if stale
    uv run check-magic-items --fix    # regenerate
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from heroforge.rules._gen_common import emit_member, enum_ident

RULES_DIR = Path(__file__).parent
CORE_MI = RULES_DIR / "core" / "magic_items"
CUSTOM_YAML = RULES_DIR / "custom" / "magic_items.yaml"
CUSTOM_PY = RULES_DIR / "custom" / "magic_items.py"

# Fixed load order — mirrors app_state.py and
# determines slot enum ordering in the combined
# KnownCoreMagicItem.
SLOTS: tuple[str, ...] = (
    "head",
    "face",
    "throat",
    "shoulders",
    "body",
    "torso",
    "arms",
    "hands",
    "ring",
    "waist",
    "feet",
    "slotless",
    "tool",
    "consumable",
)


def _render_slot_module(slot: str, names: list[str]) -> str:
    cls = f"KnownCoreMagicItem{slot.capitalize()}"
    lines = [
        '"""',
        f"{slot}.py",
        f"SRD core magic items worn in the {slot} slot.",
        "",
        "AUTO-GENERATED by _gen_magic_item_enums.py.",
        "Edit the matching YAML and rerun",
        "``uv run check-magic-items --fix``.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import StrEnum",
        "",
        "",
        f"class {cls}(StrEnum):",
    ]
    if not names:
        lines.append("    pass")
    else:
        seen: set[str] = set()
        for name in names:
            ident = enum_ident(name)
            if ident in seen:
                raise RuntimeError(
                    f"Duplicate ident {ident!r} in {slot}.yaml (from {name!r})"
                )
            seen.add(ident)
            emit_member(lines, ident, name)
    return "\n".join(lines) + "\n"


def _render_init() -> str:
    lines = [
        '"""',
        "magic_items/__init__.py",
        "-------------------------",
        "Aggregates per-slot SRD magic-item StrEnums",
        "into a single ``KnownCoreMagicItem``.",
        "",
        "AUTO-GENERATED by _gen_magic_item_enums.py.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import StrEnum",
        "",
    ]
    for slot in SLOTS:
        cls = f"KnownCoreMagicItem{slot.capitalize()}"
        lines.append(f"from heroforge.rules.core.magic_items.{slot} import (")
        lines.append(f"    {cls},")
        lines.append(")")
    lines += [
        "",
        "",
        "def _combine(",
        "    name: str, *sources: type[StrEnum]",
        ") -> type[StrEnum]:",
        "    members: dict[str, str] = {}",
        "    for src in sources:",
        "        for m in src:",
        "            members[m.name] = m.value",
        "    return StrEnum(name, members)",
        "",
        "",
        "KnownCoreMagicItem = _combine(",
        '    "KnownCoreMagicItem",',
    ]
    for slot in SLOTS:
        cls = f"KnownCoreMagicItem{slot.capitalize()}"
        lines.append(f"    {cls},")
    lines.append(")")
    return "\n".join(lines) + "\n"


def _render_custom(names: list[str]) -> str:
    lines = [
        '"""',
        "magic_items.py",
        "Custom magic items.",
        "",
        "AUTO-GENERATED by _gen_magic_item_enums.py.",
        "Edit custom/magic_items.yaml and rerun",
        "``uv run check-magic-items --fix``.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import StrEnum",
        "",
        "",
        "class KnownCustomMagicItem(StrEnum):",
    ]
    if not names:
        lines.append("    pass")
    else:
        seen: set[str] = set()
        for name in names:
            ident = enum_ident(name)
            if ident in seen:
                raise RuntimeError(
                    f"Duplicate ident {ident!r} in "
                    f"custom/magic_items.yaml "
                    f"(from {name!r})"
                )
            seen.add(ident)
            emit_member(lines, ident, name)
    return "\n".join(lines) + "\n"


def _load_names(yaml_path: Path) -> list[str]:
    data = yaml.safe_load(yaml_path.read_text()) or {}
    if not isinstance(data, dict):
        raise RuntimeError(f"{yaml_path} must be a YAML mapping")
    return list(data.keys())


def _generate() -> dict[Path, str]:
    """
    Return {path: desired_content} for every
    generated file."""
    out: dict[Path, str] = {}
    for slot in SLOTS:
        yaml_path = CORE_MI / f"{slot}.yaml"
        names = _load_names(yaml_path)
        out[CORE_MI / f"{slot}.py"] = _render_slot_module(slot, names)
    out[CORE_MI / "__init__.py"] = _render_init()
    custom_names = _load_names(CUSTOM_YAML)
    out[CUSTOM_PY] = _render_custom(custom_names)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Check that magic-item StrEnum modules match their YAML sources. "
            "Pass --fix to regenerate."
        )
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help=(
            "Regenerate every generated file from its YAML source. "
            "Default (no flag) is read-only: exit 1 if any file is stale."
        ),
    )
    args = parser.parse_args()

    desired = _generate()

    if not args.fix:
        drift: list[Path] = []
        for path, content in desired.items():
            if not path.exists() or path.read_text() != content:
                drift.append(path)
        if drift:
            print(
                "Out of sync with YAML — run "
                "``uv run check-magic-items --fix``:",
                file=sys.stderr,
            )
            for p in drift:
                print(f"  {p}", file=sys.stderr)
            return 1
        print("up to date")
        return 0

    written = 0
    for path, content in desired.items():
        if path.exists() and path.read_text() == content:
            continue
        path.write_text(content)
        written += 1
        print(f"wrote {path.relative_to(RULES_DIR)}")
    if written == 0:
        print("up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
