"""
_gen_magic_item_enums.py
-------------------------
Keep magic-item StrEnum Python files in sync with
their YAML sources.

Usage:
    uv run check-magic-items          # exit 1 if stale
    uv run check-magic-items --fix    # regenerate

Generates:
    rules/core/magic_items/<slot>.py     (per-slot, from
                                          per-slot YAML files)
    rules/core/magic_items/__init__.py   (combined KnownCoreMagicItem)
    rules/<book>/magic_items.py          (one per non-core book
                                          with a magic_items.yaml)
"""

import argparse
import os
import sys
from pathlib import Path

import yaml

from heroforge.rules._gen_common import (
    check_or_fix,
    emit_header,
    emit_import,
    emit_member,
    enum_ident,
)
from heroforge.rules.rules import CORE, RULES_DIR, book_dirs

CORE_MI = RULES_DIR / CORE / "magic_items"

# Fixed load order — mirrors app_state.py and
# determines slot enum ordering in the combined
# KnownCoreMagicItem.
SLOTS: tuple[str, ...] = (
    "arms",
    "body",
    "consumable",
    "face",
    "feet",
    "hands",
    "head",
    "ring",
    "shoulders",
    "slotless",
    "throat",
    "tool",
    "torso",
    "waist",
)


def _book_camel(book: str) -> str:
    """``"complete_warrior"`` -> ``"CompleteWarrior"``."""
    return "".join(part.capitalize() for part in book.split("_"))


def _validate_slots() -> None:
    if sorted(SLOTS) != list(SLOTS):
        print("SLOTS not sorted. Use this sorted list:")
        print("SLOTS: tuple[str, ...] = (")
        for slot in sorted(SLOTS):
            print(f'    "{slot}",')
        print(")")
        sys.exit(1)


def _render_slot_module(slot: str, names: list[str]) -> str:
    cls = f"KnownCoreMagicItem{slot.capitalize()}"
    lines = emit_header(
        filename=f"{slot}.py",
        description=f"SRD core magic items worn in the {slot} slot.",
        generator_file="_gen_magic_item_enums.py",
        toml_command="check-magic-items",
        cls_name=cls,
    )

    seen: set[str] = set()
    for name in names:
        ident = enum_ident(name)
        if ident in seen:
            raise RuntimeError(
                f"Duplicate ident {ident!r} in {slot}.yaml (from {name!r})"
            )
        seen.add(ident)
        lines += emit_member(ident, name)
    return "\n".join(lines) + "\n"


def _render_book_module(book: str, names: list[str]) -> str:
    """Render the combined ``Known<Book>MagicItem`` enum file."""
    cls = f"Known{_book_camel(book)}MagicItem"
    if book == "custom":
        description = "Custom magic items."
    else:
        nice = book.replace("_", " ").title()
        description = f"Magic items from {nice}."

    lines = emit_header(
        filename="magic_items.py",
        description=description,
        generator_file="_gen_magic_item_enums.py",
        toml_command="check-magic-items",
        cls_name=cls,
    )

    seen: set[str] = set()
    for name in names:
        ident = enum_ident(name)
        if ident in seen:
            raise RuntimeError(
                f"Duplicate ident {ident!r} in "
                f"{book}/magic_items.yaml "
                f"(from {name!r})"
            )
        seen.add(ident)
        lines.extend(emit_member(ident, name))
    return "\n".join(lines) + "\n"


def _render_init() -> str:
    lines = [
        '"""',
        "magic_items/__init__.py",
        "-------------------------",
        "Aggregates per-slot SRD magic-item StrEnums",
        "into a single ``KnownCoreMagicItem``.",
        "",
        "AUTO-GENERATED by _gen_magic_item_enums.py.",
        '"""',
        "",
        "from heroforge.rules.combine_str_enum import combine",
    ]
    for slot in SLOTS:
        lines += emit_import(
            import_path=f"heroforge.rules.core.magic_items.{slot}",
            import_name=f"KnownCoreMagicItem{slot.capitalize()}",
        )

    lines += [
        "",
        "KnownCoreMagicItem = combine(",
        '    "KnownCoreMagicItem",',
    ]
    for slot in SLOTS:
        cls = f"KnownCoreMagicItem{slot.capitalize()}"
        lines.append(f"    {cls},")
    lines.append(")")
    return "\n".join(lines) + "\n"


def _load_names(yaml_path: Path) -> list[str]:
    data = yaml.safe_load(yaml_path.read_text()) or {}
    if not isinstance(data, dict):
        raise RuntimeError(f"{yaml_path} must be a YAML mapping")
    return list(data.keys())


def _generate() -> dict[Path, str]:
    """
    Return {path: desired_content} for every
    generated file."""
    out: dict[Path, str] = {}

    # core/ uses per-slot files plus a combined __init__.py.
    for slot in SLOTS:
        yaml_path = CORE_MI / f"{slot}.yaml"
        names = _load_names(yaml_path)
        out[CORE_MI / f"{slot}.py"] = _render_slot_module(slot, names)
    out[CORE_MI / "__init__.py"] = _render_init()

    # Every non-core book with a magic_items.yaml gets a single
    # combined magic_items.py.
    for book in book_dirs(RULES_DIR):
        if book == CORE:
            continue
        mi_yaml = RULES_DIR / book / "magic_items.yaml"
        if not mi_yaml.exists():
            continue
        names = _load_names(mi_yaml)
        out[RULES_DIR / book / "magic_items.py"] = _render_book_module(
            book, names
        )
    return out


def main(argv: list[str] | None = None) -> int:
    """
    Check that magic-item StrEnum modules match their YAML sources.
    Pass --fix to regenerate.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Check that magic-item StrEnum modules match their YAML sources. "
            "Pass --fix to regenerate."
        )
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help=(
            "Regenerate every generated file from its YAML source. "
            "Default (no flag) is read-only: exit 1 if any file is stale."
        ),
    )
    args = parser.parse_args(argv)

    _validate_slots()
    desired = _generate()

    check_ok = check_or_fix(desired, args.fix, "check-magic-items", RULES_DIR)
    return os.EX_OK if check_ok else os.EX_SOFTWARE


if __name__ == "__main__":
    raise SystemExit(main())
