"""
_gen_magic_item_enums.py
-------------------------
Keep magic-item StrEnum Python files in sync with
their YAML sources.

Usage:
    uv run check-magic-items          # exit 1 if stale
    uv run check-magic-items --fix    # regenerate
"""

import argparse
import os
import sys
from pathlib import Path

import yaml

from heroforge.rules._gen_common import (
    check_or_fix,
    emit_header,
    emit_import,
    emit_member,
    enum_ident,
)

RULES_DIR = Path(__file__).parent
CORE_MI = RULES_DIR / "core" / "magic_items"
CUSTOM_YAML = RULES_DIR / "custom" / "magic_items.yaml"
CUSTOM_PY = RULES_DIR / "custom" / "magic_items.py"

# Fixed load order — mirrors app_state.py and
# determines slot enum ordering in the combined
# KnownCoreMagicItem.
SLOTS: tuple[str, ...] = (
    "arms",
    "body",
    "consumable",
    "face",
    "feet",
    "hands",
    "head",
    "ring",
    "shoulders",
    "slotless",
    "throat",
    "tool",
    "torso",
    "waist",
)


def _validate_slots() -> None:
    if sorted(SLOTS) != list(SLOTS):
        print("SLOTS not sorted. Use this sorted list:")
        print("SLOTS: tuple[str, ...] = (")
        for slot in sorted(SLOTS):
            print(f'    "{slot}",')
        print(")")
        sys.exit(1)


def _render_slot_module(slot: str, names: list[str]) -> str:
    cls = f"KnownCoreMagicItem{slot.capitalize()}"
    lines = emit_header(
        filename=f"{slot}.py",
        description=f"SRD core magic items worn in the {slot} slot.",
        generator_file="_gen_magic_item_enums.py",
        toml_command="check-magic-items",
        cls_name=cls,
    )

    seen: set[str] = set()
    for name in names:
        ident = enum_ident(name)
        if ident in seen:
            raise RuntimeError(
                f"Duplicate ident {ident!r} in {slot}.yaml (from {name!r})"
            )
        seen.add(ident)
        lines += emit_member(ident, name)
    return "\n".join(lines) + "\n"


def _render_custom(names: list[str]) -> str:
    lines = emit_header(
        filename="magic_items.py",
        description="Custom magic items.",
        generator_file="_gen_magic_item_enums.py",
        toml_command="check-magic-items",
        cls_name="KnownCustomMagicItem",
    )

    seen: set[str] = set()
    for name in names:
        ident = enum_ident(name)
        if ident in seen:
            raise RuntimeError(
                f"Duplicate ident {ident!r} in "
                f"custom/magic_items.yaml "
                f"(from {name!r})"
            )
        seen.add(ident)
        lines.extend(emit_member(ident, name))
    return "\n".join(lines) + "\n"


def _render_init() -> str:
    lines = [
        '"""',
        "magic_items/__init__.py",
        "-------------------------",
        "Aggregates per-slot SRD magic-item StrEnums",
        "into a single ``KnownCoreMagicItem``.",
        "",
        "AUTO-GENERATED by _gen_magic_item_enums.py.",
        '"""',
        "",
        "from heroforge.rules.combine_str_enum import combine",
    ]
    for slot in SLOTS:
        lines += emit_import(
            import_path=f"heroforge.rules.core.magic_items.{slot}",
            import_name=f"KnownCoreMagicItem{slot.capitalize()}",
        )

    lines += [
        "",
        "KnownCoreMagicItem = combine(",
        '    "KnownCoreMagicItem",',
    ]
    for slot in SLOTS:
        cls = f"KnownCoreMagicItem{slot.capitalize()}"
        lines.append(f"    {cls},")
    lines.append(")")
    return "\n".join(lines) + "\n"


def _load_names(yaml_path: Path) -> list[str]:
    data = yaml.safe_load(yaml_path.read_text()) or {}
    if not isinstance(data, dict):
        raise RuntimeError(f"{yaml_path} must be a YAML mapping")
    return list(data.keys())


def _generate() -> dict[Path, str]:
    """
    Return {path: desired_content} for every
    generated file."""
    out: dict[Path, str] = {}
    for slot in SLOTS:
        yaml_path = CORE_MI / f"{slot}.yaml"
        names = _load_names(yaml_path)
        out[CORE_MI / f"{slot}.py"] = _render_slot_module(slot, names)
    out[CORE_MI / "__init__.py"] = _render_init()
    custom_names = _load_names(CUSTOM_YAML)
    out[CUSTOM_PY] = _render_custom(custom_names)
    return out


def main(argv: list[str] | None = None) -> int:
    """
    Check that magic-item StrEnum modules match their YAML sources.
    Pass --fix to regenerate.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Check that magic-item StrEnum modules match their YAML sources. "
            "Pass --fix to regenerate."
        )
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help=(
            "Regenerate every generated file from its YAML source. "
            "Default (no flag) is read-only: exit 1 if any file is stale."
        ),
    )
    args = parser.parse_args(argv)

    _validate_slots()
    desired = _generate()

    check_ok = check_or_fix(desired, args.fix, "check-magic-items", RULES_DIR)
    return os.EX_OK if check_ok else os.EX_SOFTWARE


if __name__ == "__main__":
    raise SystemExit(main())
