"""
_gen_pool_keys.py
------------------
Keep ``rules/core/pool_keys.py`` in sync with its YAML sources.

The ``PoolKey`` StrEnum is the closed set of BonusPool
identifiers used throughout the engine. Its members come from
two sources:

  - stats.yaml  — every ``pools:`` entry across every stat node
  - skills.yaml — one member per skill, named
                  ``SKILL_<enum_ident(name)>`` with value
                  ``"skill_<snake(enum_ident(name))>"``.

Usage:
    uv run check-pool-keys          # exit 1 if stale
    uv run check-pool-keys --fix    # regenerate
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from heroforge.rules._gen_common import emit_member, enum_ident

RULES_DIR = Path(__file__).parent
CORE_DIR = RULES_DIR / "core"
STATS_YAML = CORE_DIR / "stats.yaml"
SKILLS_YAML = CORE_DIR / "skills.yaml"
OUT_FILE = CORE_DIR / "pool_keys.py"

# Pools registered in engine/character.py bootstrap that aren't
# (yet) reflected in stats.yaml. Kept here so PoolKey stays
# complete — move them into stats.yaml when/if the bootstrap is
# unified with the YAML stat graph.
_EXTRA_POOL_KEYS: tuple[str, ...] = (
    "grapple",
    "damage_ranged",
)


def _stat_pool_refs() -> list[str]:
    """
    Collect every pool key referenced in stats.yaml plus any
    ``_EXTRA_POOL_KEYS`` the engine registers in Python, in
    first-occurrence order (stable for diffs).
    """
    data = yaml.safe_load(STATS_YAML.read_text()) or []
    seen: list[str] = []
    seen_set: set[str] = set()
    for decl in data:
        for pk in decl.get("pools", []) or []:
            if pk not in seen_set:
                seen.append(pk)
                seen_set.add(pk)
    for pk in _EXTRA_POOL_KEYS:
        if pk not in seen_set:
            seen.append(pk)
            seen_set.add(pk)
    return seen


def _skill_entries() -> list[tuple[str, str]]:
    """
    Return (ident, value) tuples for every skill. ``ident`` is
    ``SKILL_<enum_ident(name)>``; ``value`` is the lowercase
    form used as the BonusPool stat_key.
    """
    data = yaml.safe_load(SKILLS_YAML.read_text()) or {}
    out: list[tuple[str, str]] = []
    seen: set[str] = set()
    for name in data:
        ident = f"SKILL_{enum_ident(name)}"
        if ident in seen:
            raise RuntimeError(
                f"Duplicate PoolKey ident {ident!r} from skill {name!r}"
            )
        seen.add(ident)
        out.append((ident, f"skill_{enum_ident(name).lower()}"))
    return out


def _skill_name_map(
    data: dict[str, object], pairs: list[tuple[str, str]]
) -> list[tuple[str, str]]:
    """Return [(skill_name, ident), ...] in YAML order."""
    names = list(data.keys())
    assert len(names) == len(pairs)
    return list(zip(names, [ident for ident, _ in pairs], strict=True))


def _render() -> str:
    stat_vals = _stat_pool_refs()
    skill_pairs = _skill_entries()
    skills_data = yaml.safe_load(SKILLS_YAML.read_text()) or {}
    name_map = _skill_name_map(skills_data, skill_pairs)

    lines = [
        '"""',
        "rules/core/pool_keys.py",
        "------------------------",
        "Closed set of BonusPool identifiers used by the engine.",
        "",
        "AUTO-GENERATED by _gen_pool_keys.py. Edit stats.yaml or",
        "skills.yaml and rerun ``uv run check-pool-keys --fix``.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import StrEnum",
        "",
        "",
        "class PoolKey(StrEnum):",
    ]
    if not stat_vals and not skill_pairs:
        lines.append("    pass")
    else:
        seen: set[str] = set()
        for val in stat_vals:
            ident = val.upper()
            if ident in seen:
                raise RuntimeError(
                    f"Duplicate PoolKey ident {ident!r} from stats.yaml"
                )
            seen.add(ident)
            emit_member(lines, ident, val)
        for ident, val in skill_pairs:
            if ident in seen:
                raise RuntimeError(
                    f"Duplicate PoolKey ident {ident!r} (skill vs stats)"
                )
            seen.add(ident)
            emit_member(lines, ident, val)

    lines += [
        "",
        "",
        "_SKILL_NAME_TO_POOL_KEY: dict[str, PoolKey] = {",
    ]
    for skill_name, ident in name_map:
        single = f'    "{skill_name}": PoolKey.{ident},'
        if len(single) <= 80:
            lines.append(single)
        else:
            lines.append(f'    "{skill_name}": (')
            lines.append(f"        PoolKey.{ident}")
            lines.append("    ),")
    lines += [
        "}",
        "",
        "",
        "def pool_key_for_skill(name: str) -> PoolKey:",
        '    """Return the PoolKey that backs a skill named ``name``."""',
        "    try:",
        "        return _SKILL_NAME_TO_POOL_KEY[name]",
        "    except KeyError as exc:",
        '        msg = f"No PoolKey registered for skill {name!r}"',
        "        raise KeyError(msg) from exc",
    ]
    return "\n".join(lines) + "\n"


def generate() -> dict[Path, str]:
    """Return {path: desired_content} for every generated file."""
    return {OUT_FILE: _render()}


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Check that pool_keys.py matches its YAML sources. "
            "Pass --fix to regenerate."
        )
    )
    parser.add_argument(
        "--fix",
        action="store_true",
        help=(
            "Regenerate pool_keys.py from its YAML sources. "
            "Default (no flag) is read-only: exit 1 if stale."
        ),
    )
    args = parser.parse_args()

    desired = generate()

    if not args.fix:
        drift: list[Path] = []
        for path, content in desired.items():
            if not path.exists() or path.read_text() != content:
                drift.append(path)
        if drift:
            print(
                "Out of sync with YAML — run ``uv run check-pool-keys --fix``:",
                file=sys.stderr,
            )
            for p in drift:
                print(f"  {p}", file=sys.stderr)
            return 1
        print("up to date")
        return 0

    written = 0
    for path, content in desired.items():
        if path.exists() and path.read_text() == content:
            continue
        path.write_text(content)
        written += 1
        print(f"wrote {path.relative_to(RULES_DIR)}")
    if written == 0:
        print("up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
