"""
_gen_common.py
---------------
Shared helpers for YAML-to-StrEnum code generators
(_gen_magic_item_enums, _gen_pool_keys, etc.).
"""

import re
import sys
from pathlib import Path


def enum_ident(name: str) -> str:
    """
    Convert a display name into an enum identifier
    (UPPER_SNAKE, ASCII only)."""
    s = name
    s = s.replace("+", "plus ")
    s = s.replace("'", "")
    s = s.replace("(", " ").replace(")", " ")
    s = s.replace("/", " ")
    s = s.replace(",", " ")
    s = s.replace(".", " ")
    s = s.replace("-", " ")
    s = s.replace("&", " and ")
    s = re.sub(r"\s+", " ", s).strip()
    return s.replace(" ", "_").upper()


def emit_header(
    *,
    filename: str,
    description: str,
    generator_file: str,
    toml_command: str,
    extra_imports: list[tuple[str, str]] | None = None,
    cls_name: str,
) -> list[str]:
    """
    Emit the header for a Python file.
    """
    prefix = [
        '"""',
        f"{filename}",
        f"{description}",
        "",
        f"AUTO-GENERATED by {generator_file}.",
        "Edit the matching YAML and rerun",
        f"``uv run {toml_command} --fix``.",
        '"""',
        "",
        "from enum import StrEnum",
    ]

    extra = []
    if extra_imports:
        extra.append("")
        for import_path, import_name in extra_imports:
            extra.extend(
                emit_import(import_path=import_path, import_name=import_name)
            )

    suffix = [
        "",
        "",
        f"class {cls_name}(StrEnum):",
    ]

    return prefix + extra + suffix


def emit_member(ident: str, val: str) -> list[str]:
    """
    Append a StrEnum member line to ``lines``.
    Wraps long single-line members onto three lines
    to keep the 80-column limit.
    """
    single = f'    {ident} = "{val}"'
    if len(single) <= 80:
        return [single]

    return [
        f"    {ident} = (",
        f'        "{val}"',
        "    )",
    ]


def emit_import(*, import_path: str, import_name: str) -> list[str]:
    """
    Emit an import line for a Python file.
    """
    single = f"from {import_path} import {import_name}"
    if len(single) <= 80:
        return [single]
    return [
        f"from {import_path} import (",
        f"    {import_name},",
        ")",
    ]


def check_or_fix(
    desired: dict[Path, str], fix: bool, checker_name: str, base_dir: Path
) -> bool:
    """
    Check if the desired content is up to date.

    If fix is True, additionally write the updated contents to the files.

    Returns True if the content is up to date before this function is called,
        otherwise False.
    """
    drift: list[Path] = []
    for path, content in desired.items():
        if not path.exists() or path.read_text() != content:
            drift.append(path)

    if not drift:
        print("up to date")
        return True

    if fix:
        for path, content in desired.items():
            if path.exists() and path.read_text() == content:
                continue
            path.write_text(content)
            print(f"wrote {path.relative_to(base_dir)}")
    else:
        print(
            f"Out of sync with YAML — run ``uv run {checker_name} --fix``:",
            file=sys.stderr,
        )
        for p in drift:
            print(f"  {p.relative_to(base_dir)}", file=sys.stderr)

    return False
