"""
known.pyi
---------
Type-checker view of the combined KnownXxx enums.

``known.py`` assembles each of these with ``combine()`` at
import time, by scanning the book directories. That is the
point of the module — a new splatbook folder needs no edits
there — but it means the names are *values* holding enum
classes, not class declarations, so a type checker cannot
use them in an annotation (``dict[KnownSkill, int]``) or
see them as callable enum constructors.

This stub declares the classes and nothing else. Members
are deliberately absent: they are discovered at runtime, so
listing them here would be a second copy free to drift from
the books. Member access (``KnownRace.HUMAN``) is therefore
an error, which is correct — use the constructor,
``KnownRace(name)``, as every caller already does.

Congruence between these enums and the live registries is
tested in ``rules/test/known_test.py``.
"""

from enum import StrEnum

# Core-only categories.
class KnownArmor(StrEnum): ...
class KnownBuff(StrEnum): ...
class KnownCondition(StrEnum): ...
class KnownDeity(StrEnum): ...
class KnownDomain(StrEnum): ...
class KnownGate(StrEnum): ...
class KnownRace(StrEnum): ...
class KnownSkill(StrEnum): ...
class KnownTemplate(StrEnum): ...
class KnownWeapon(StrEnum): ...

# Per-book categories, discovered across every book.
class KnownAcf(StrEnum): ...
class KnownClass(StrEnum): ...
class KnownFeat(StrEnum): ...
class KnownMagicItem(StrEnum): ...
class KnownMaterial(StrEnum): ...
