"""
tests/test_gen_common.py
-------------------------
Unit tests for the shared code-generator helpers in
``heroforge.rules._gen_common``. These helpers underpin every
``check-*`` generator, so pinning their behaviour directly
(rather than only indirectly via idempotency tests) catches
regressions in the helpers themselves.
"""

from __future__ import annotations

from pathlib import Path

from heroforge.rules._gen_common import (
    check_or_fix,
    emit_header,
    emit_import,
    emit_member,
    enum_ident,
)

# ---------------------------------------------------------------------------
# enum_ident
# ---------------------------------------------------------------------------


def test_enum_ident_simple() -> None:
    assert enum_ident("Power Attack") == "POWER_ATTACK"


def test_enum_ident_apostrophe_is_stripped() -> None:
    assert enum_ident("Bag o' Gold") == "BAG_O_GOLD"


def test_enum_ident_plus_becomes_plus_word() -> None:
    assert enum_ident("Sword +1") == "SWORD_PLUS_1"


def test_enum_ident_ampersand_becomes_and() -> None:
    assert enum_ident("Bell & Whistle") == "BELL_AND_WHISTLE"


def test_enum_ident_punctuation_becomes_underscore() -> None:
    # parens, slash, comma, period, dash all collapse to a single
    # underscore after whitespace normalisation.
    assert enum_ident("Foo (bar)") == "FOO_BAR"
    assert enum_ident("Foo/Bar") == "FOO_BAR"
    assert enum_ident("Foo, Bar") == "FOO_BAR"
    assert enum_ident("Foo.Bar") == "FOO_BAR"
    assert enum_ident("Foo-Bar") == "FOO_BAR"


def test_enum_ident_collapses_runs_of_whitespace() -> None:
    assert enum_ident("Foo   Bar") == "FOO_BAR"
    assert enum_ident("  Foo  Bar  ") == "FOO_BAR"


# ---------------------------------------------------------------------------
# emit_member
# ---------------------------------------------------------------------------


def test_emit_member_short_is_single_line() -> None:
    out = emit_member("FOO", "foo")
    assert out == ['    FOO = "foo"']
    assert len(out[0]) <= 80


def test_emit_member_long_wraps_to_three_lines() -> None:
    long_val = "x" * 90
    out = emit_member("FOO", long_val)
    assert out == [
        "    FOO = (",
        f'        "{long_val}"',
        "    )",
    ]


def test_emit_member_at_80_col_boundary_stays_single_line() -> None:
    # Single-line form = 9 + len(ident) + len(val); pick lengths
    # that land exactly on 80.
    ident = "A" * 10
    val = "b" * 61
    single = f'    {ident} = "{val}"'
    assert len(single) == 80
    assert emit_member(ident, val) == [single]


# ---------------------------------------------------------------------------
# emit_import
# ---------------------------------------------------------------------------


def test_emit_import_short_is_single_line() -> None:
    out = emit_import(import_path="foo.bar", import_name="Baz")
    assert out == ["from foo.bar import Baz"]


def test_emit_import_long_wraps_to_three_lines() -> None:
    long_path = "a.very." + "long." * 15 + "module"
    out = emit_import(import_path=long_path, import_name="Thing")
    assert out == [
        f"from {long_path} import (",
        "    Thing,",
        ")",
    ]


# ---------------------------------------------------------------------------
# emit_header
# ---------------------------------------------------------------------------


def test_emit_header_basic() -> None:
    lines = emit_header(
        filename="foo.py",
        description="Test file.",
        generator_file="_gen_foo.py",
        toml_command="check-foo",
        cls_name="KnownFoo",
    )
    assert lines[0] == '"""'
    assert "foo.py" in lines
    assert "Test file." in lines
    assert "AUTO-GENERATED by _gen_foo.py." in lines
    assert "``uv run check-foo --fix``." in lines
    assert "from enum import StrEnum" in lines
    assert lines[-1] == "class KnownFoo(StrEnum):"


def test_emit_header_with_extra_imports_places_them_before_class() -> None:
    lines = emit_header(
        filename="foo.py",
        description="Test file.",
        generator_file="_gen_foo.py",
        toml_command="check-foo",
        extra_imports=[
            ("heroforge.rules.combine_str_enum", "combine"),
            ("heroforge.rules.core.skills", "KnownCoreSkill"),
        ],
        cls_name="KnownFoo",
    )
    enum_idx = lines.index("from enum import StrEnum")
    class_idx = lines.index("class KnownFoo(StrEnum):")
    combine_idx = lines.index(
        "from heroforge.rules.combine_str_enum import combine"
    )
    skills_idx = lines.index(
        "from heroforge.rules.core.skills import KnownCoreSkill"
    )
    assert enum_idx < combine_idx < class_idx
    assert enum_idx < skills_idx < class_idx


# ---------------------------------------------------------------------------
# check_or_fix
# ---------------------------------------------------------------------------


def test_check_or_fix_returns_true_when_up_to_date(
    tmp_path: Path,
) -> None:
    target = tmp_path / "out.py"
    target.write_text("hello\n")
    desired = {target: "hello\n"}
    assert check_or_fix(desired, fix=False, checker_name="x", base_dir=tmp_path)
    # Content unchanged.
    assert target.read_text() == "hello\n"


def test_check_or_fix_returns_false_on_drift_without_fix(
    tmp_path: Path,
) -> None:
    target = tmp_path / "out.py"
    target.write_text("stale\n")
    desired = {target: "fresh\n"}
    assert not check_or_fix(
        desired, fix=False, checker_name="x", base_dir=tmp_path
    )
    # fix=False must not mutate the file.
    assert target.read_text() == "stale\n"


def test_check_or_fix_writes_when_fix_is_true(tmp_path: Path) -> None:
    target = tmp_path / "out.py"
    target.write_text("stale\n")
    desired = {target: "fresh\n"}
    # Still returns False (the *pre-call* state was stale).
    assert not check_or_fix(
        desired, fix=True, checker_name="x", base_dir=tmp_path
    )
    assert target.read_text() == "fresh\n"


def test_check_or_fix_creates_missing_file_when_fix_is_true(
    tmp_path: Path,
) -> None:
    target = tmp_path / "nested" / "out.py"
    target.parent.mkdir()
    desired = {target: "fresh\n"}
    assert not check_or_fix(
        desired, fix=True, checker_name="x", base_dir=tmp_path
    )
    assert target.read_text() == "fresh\n"


def test_check_or_fix_reports_each_drifting_file(
    tmp_path: Path, capsys: object
) -> None:
    a = tmp_path / "a.py"
    b = tmp_path / "b.py"
    a.write_text("old-a\n")
    b.write_text("new-b\n")
    desired = {a: "new-a\n", b: "new-b\n"}
    assert not check_or_fix(
        desired, fix=False, checker_name="check-x", base_dir=tmp_path
    )
    err = capsys.readouterr().err  # type: ignore[attr-defined]
    assert "check-x" in err
    assert "a.py" in err
    assert "b.py" not in err
